/**
 * Node Builder
 *
 * Implements the Builder pattern for creating Node objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type { NodeInterface, NodeType } from "./node.interface";
import { NodeSchema } from "./node.schema";

/**
 * NodeBuilder class
 *
 * Provides a fluent API for building Node objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class NodeBuilder {
  private data: Partial<NodeInterface> = {};

  constructor() {
    // Set sensible defaults
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      parent: null,
      type: "file",
      title: "New Node",
      order: 0,
      collapsed: true,
      createDate: now,
      lastEdit: now,
    };
  }

  /**
   * Set the workspace ID this node belongs to
   * @param id - UUID of the parent workspace
   * @returns this builder for chaining
   */
  workspace(id: string): this {
    this.data.workspace = id;
    return this;
  }

  /**
   * Set the parent node ID
   * @param id - UUID of the parent node, or null for root-level
   * @returns this builder for chaining
   */
  parent(id: string | null): this {
    this.data.parent = id;
    return this;
  }

  /**
   * Set the node type
   * @param type - The type of node ("folder" | "file" | "canvas" | "diary")
   * @returns this builder for chaining
   */
  type(type: NodeType): this {
    this.data.type = type;
    return this;
  }

  /**
   * Set the node title
   * @param title - Display title for the node
   * @returns this builder for chaining
   */
  title(title: string): this {
    this.data.title = title;
    return this;
  }

  /**
   * Set the sort order
   * @param order - Sort order among siblings (0-based)
   * @returns this builder for chaining
   */
  order(order: number): this {
    this.data.order = order;
    return this;
  }

  /**
   * Set the collapsed state
   * @param collapsed - Whether the folder is collapsed
   * @returns this builder for chaining
   */
  collapsed(collapsed: boolean): this {
    this.data.collapsed = collapsed;
    return this;
  }

  /**
   * Set a custom ID (optional, auto-generated by default)
   * @param id - UUID for the node
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set a custom createDate timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  createDate(timestamp: string): this {
    this.data.createDate = timestamp;
    return this;
  }

  /**
   * Set a custom lastEdit timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  lastEdit(timestamp: string): this {
    this.data.lastEdit = timestamp;
    return this;
  }

  /**
   * Set the tags array
   * @param tags - Array of tag strings
   * @returns this builder for chaining
   */
  tags(tags: string[]): this {
    this.data.tags = tags;
    return this;
  }

  /**
   * Build and validate the Node object
   * @returns A validated NodeInterface object
   * @throws ZodError if validation fails
   */
  build(): NodeInterface {
    // Update lastEdit to current time if not explicitly set after construction
    const now = dayjs().toISOString();
    if (!this.data.lastEdit) {
      this.data.lastEdit = now;
    }
    if (!this.data.createDate) {
      this.data.createDate = now;
    }

    // Validate and return
    const result = NodeSchema.parse(this.data);
    return result as NodeInterface;
  }

  /**
   * Build a partial Node object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial NodeInterface object with updated lastEdit
   */
  buildPartial(): Partial<NodeInterface> {
    // Always update lastEdit for partial builds
    this.data.lastEdit = dayjs().toISOString();
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      parent: null,
      type: "file",
      title: "New Node",
      order: 0,
      collapsed: true,
      createDate: now,
      lastEdit: now,
    };
    return this;
  }
}
