/**
 * 工具函数导出
 * Utility functions exports for ESLint plugin
 */

// 重导出类型和配置
export * from "../types/index.js"
// 架构层级工具
export {
	getAllowedDependencies,
	getArchitectureLayer,
	getContainerExtraDependencies,
	getDeprecatedDirectoryMigration,
	getExpectedTestFilePath,
	getImportLayer,
	getLayerChineseName,
	getLayerDescription,
	getLayerViolationDetails,
	getRelativeImportDepth,
	getSuggestedDirectory,
	isAliasImport,
	isContainerComponent,
	isDeprecatedDirectoryImport,
	isExternalImport,
	isFileInCorrectDirectory,
	isIndexFilePattern,
	isInternalImport,
	isLayerViolation,
	isRelativeImport,
	isRelativeImportTooDeep,
	isTestFile,
	isViewComponent,
} from "./architecture.js"

// AST 辅助函数
export {
	getCallExpressionDepth,
	getConsoleMethodName,
	getFunctionLineCount,
	getFunctionName,
	getFunctionParamCount,
	getImportSource,
	getMemberMethodName,
	getMemberObjectName,
	getNamedImports,
	getNestingDepth,
	hasDefaultImport,
	hasNamedImports,
	isArrayIndexAssignment,
	isAssignmentExpression,
	isAsyncFunction,
	isAwaitExpression,
	isConsoleCall,
	isDangerouslySetInnerHTML,
	isEvalCall,
	isFunctionConstructor,
	isGlobalIdentifier,
	isInnerHTMLAssignment,
	isInsideAsyncFunction,
	isInsideJSXAttribute,
	isInTestFile,
	isJSXElement,
	isMemberMethodCall,
	isMethodCall,
	isNewPromise,
	isObjectPropertyAssignment,
	isPromiseMethodCall,
	isReactFunctionComponent,
	isThrowStatement,
	isTryCatchStatement,
} from "./ast-helpers.js"
// 消息构建器
export {
	buildComprehensiveErrorMessage,
	buildErrorMessage,
	buildShortErrorMessage,
	buildShortWarningMessage,
	buildSuggestionMessage,
	buildWarningMessage,
	getImmutableArrayAlternative,
	getLayerViolationSuggestion,
	getOptionMigrationExample,
	getTaskEitherMigrationExample,
} from "./message-builder.js"
// 命名检查辅助
export {
	camelToKebab,
	camelToScreamingSnake,
	getBooleanNameIssue,
	getConstantNameIssue,
	getEventHandlerNameIssue,
	getFunctionNameIssue,
	getVariableNameIssue,
	hasValidBooleanPrefix,
	hasValidEventHandlerPrefix,
	isCamelCase,
	isKebabCase,
	isPascalCase,
	isPrivateName,
	isScreamingSnakeCase,
	isSnakeCase,
	isValidComponentName,
	isValidDirectoryName,
	isValidFileName,
	isValidHookName,
	isValidTypeName,
	isValidVariableLength,
	kebabToCamel,
	snakeToCamel,
	startsWithVerb,
	suggestBooleanName,
	suggestConstantName,
	suggestEventHandlerName,
} from "./naming-helpers.js"
