/**
 * Drawing Builder
 *
 * Implements the Builder pattern for creating Drawing objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type { DrawingInterface } from "./drawing.interface";
import { DrawingSchema, DEFAULT_DRAWING_WIDTH, DEFAULT_DRAWING_HEIGHT } from "./drawing.schema";

/**
 * DrawingBuilder class
 *
 * Provides a fluent API for building Drawing objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class DrawingBuilder {
  private data: Partial<DrawingInterface> = {};

  constructor() {
    // Set sensible defaults
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      name: "New Drawing",
      content: "",
      width: DEFAULT_DRAWING_WIDTH,
      height: DEFAULT_DRAWING_HEIGHT,
      createDate: now,
      updatedAt: now,
    };
  }

  /**
   * Set the drawing ID (optional, auto-generated by default)
   * @param id - UUID for the drawing
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set the project/workspace ID
   * @param projectId - UUID of the project this drawing belongs to
   * @returns this builder for chaining
   */
  project(projectId: string): this {
    this.data.project = projectId;
    return this;
  }

  /**
   * Set the drawing name
   * @param name - Display name for the drawing
   * @returns this builder for chaining
   */
  name(name: string): this {
    this.data.name = name;
    return this;
  }

  /**
   * Set the drawing content
   * @param content - Excalidraw JSON data as string
   * @returns this builder for chaining
   */
  content(content: string): this {
    this.data.content = content;
    return this;
  }

  /**
   * Set the drawing width
   * @param width - Canvas width in pixels
   * @returns this builder for chaining
   */
  width(width: number): this {
    this.data.width = width;
    return this;
  }

  /**
   * Set the drawing height
   * @param height - Canvas height in pixels
   * @returns this builder for chaining
   */
  height(height: number): this {
    this.data.height = height;
    return this;
  }

  /**
   * Set both width and height at once
   * @param width - Canvas width in pixels
   * @param height - Canvas height in pixels
   * @returns this builder for chaining
   */
  dimensions(width: number, height: number): this {
    this.data.width = width;
    this.data.height = height;
    return this;
  }

  /**
   * Set the createDate timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  createDate(timestamp: string): this {
    this.data.createDate = timestamp;
    return this;
  }

  /**
   * Set the updatedAt timestamp
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  updatedAt(timestamp: string): this {
    this.data.updatedAt = timestamp;
    return this;
  }

  /**
   * Build and validate the Drawing object
   * @returns A validated DrawingInterface object
   * @throws ZodError if validation fails
   */
  build(): DrawingInterface {
    // Update timestamps if not explicitly set
    const now = dayjs().toISOString();
    if (!this.data.createDate) {
      this.data.createDate = now;
    }
    if (!this.data.updatedAt) {
      this.data.updatedAt = now;
    }

    // Validate and return
    const result = DrawingSchema.parse(this.data);
    return result as DrawingInterface;
  }

  /**
   * Build a partial Drawing object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial DrawingInterface object with updated timestamp
   */
  buildPartial(): Partial<DrawingInterface> {
    // Always update updatedAt for partial builds
    this.data.updatedAt = dayjs().toISOString();
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      name: "New Drawing",
      content: "",
      width: DEFAULT_DRAWING_WIDTH,
      height: DEFAULT_DRAWING_HEIGHT,
      createDate: now,
      updatedAt: now,
    };
    return this;
  }
}
