/**
 * 完整主题配置系统 - VS Code 风格
 */

export interface ThemeColors {
	// 基础背景
	background: string;
	foreground: string;
	card: string;
	cardForeground: string;
	popover: string;
	popoverForeground: string;

	// 主色调
	primary: string;
	primaryForeground: string;

	// 次要色
	secondary: string;
	secondaryForeground: string;

	// 柔和色
	muted: string;
	mutedForeground: string;

	// 强调色
	accent: string;
	accentForeground: string;

	// 边框和输入
	border: string;
	input: string;
	ring: string;

	// 侧边栏
	sidebar: string;
	sidebarForeground: string;
	sidebarPrimary: string;
	sidebarPrimaryForeground: string;
	sidebarAccent: string;
	sidebarAccentForeground: string;
	sidebarBorder: string;
	folderColor: string;

	// Toast 提示框（可选）
	toastBackground?: string;
	toastForeground?: string;
	toastBorder?: string;

	// 编辑器扩展颜色
	editorCursor?: string;
	editorSelection: string; // Required - background color for selected text
	editorLineHighlight?: string;

	// 状态颜色（可选）
	success?: string;
	warning?: string;
	error?: string;
	info?: string;

	// 编辑器语法高亮（可选）
	syntaxHeading?: string;
	syntaxBold?: string;
	syntaxItalic?: string;
	syntaxLink?: string;
	syntaxCode?: string;
	syntaxQuote?: string;
	syntaxComment?: string;
}

export interface Theme {
	key: string;
	name: string;
	description: string;
	type: "light" | "dark";
	colors: ThemeColors;
}

export const themes: Theme[] = [
	// ============ 浅色主题 ============
	{
		key: "default-light",
		name: "Default Light",
		description: "默认浅色主题",
		type: "light",
		colors: {
			background: "#ffffff",
			foreground: "#1f2937",
			card: "#ffffff",
			cardForeground: "#1f2937",
			popover: "#ffffff",
			popoverForeground: "#1f2937",
			primary: "#2563eb",
			primaryForeground: "#ffffff",
			secondary: "#f3f4f6",
			secondaryForeground: "#1f2937",
			muted: "#f3f4f6",
			mutedForeground: "#6b7280",
			accent: "#eff6ff",
			accentForeground: "#1f2937",
			border: "#e5e7eb",
			input: "#e5e7eb",
			ring: "#2563eb",
			sidebar: "#f9fafb",
			sidebarForeground: "#1f2937",
			sidebarPrimary: "#2563eb",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#eff6ff",
			sidebarAccentForeground: "#1f2937",
			sidebarBorder: "#e5e7eb",
			folderColor: "#3b82f6",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#1f2937",
			toastBorder: "#e5e7eb",
			// 编辑器扩展颜色
			editorCursor: "#2563eb",
			editorSelection: "#bfdbfe",
			editorLineHighlight: "#f8fafc",
		},
	},
	{
		key: "github-light",
		name: "GitHub Light",
		description: "GitHub 浅色主题",
		type: "light",
		colors: {
			background: "#ffffff",
			foreground: "#24292f",
			card: "#ffffff",
			cardForeground: "#24292f",
			popover: "#ffffff",
			popoverForeground: "#24292f",
			primary: "#0969da",
			primaryForeground: "#ffffff",
			secondary: "#f6f8fa",
			secondaryForeground: "#24292f",
			muted: "#f6f8fa",
			mutedForeground: "#57606a",
			accent: "#ddf4ff",
			accentForeground: "#24292f",
			border: "#d0d7de",
			input: "#d0d7de",
			ring: "#0969da",
			sidebar: "#f6f8fa",
			sidebarForeground: "#24292f",
			sidebarPrimary: "#0969da",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#ddf4ff",
			sidebarAccentForeground: "#24292f",
			sidebarBorder: "#d0d7de",
			folderColor: "#58a6ff",
			// 编辑器扩展颜色
			editorCursor: "#0969da",
			editorSelection: "#b6e3ff",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#24292f",
			toastBorder: "#d0d7de",
			editorLineHighlight: "#f6f8fa",
		},
	},
	{
		key: "solarized-light",
		name: "Solarized Light",
		description: "护眼浅色主题",
		type: "light",
		colors: {
			background: "#fdf6e3",
			foreground: "#657b83",
			card: "#fdf6e3",
			cardForeground: "#657b83",
			popover: "#fdf6e3",
			popoverForeground: "#657b83",
			primary: "#268bd2",
			primaryForeground: "#fdf6e3",
			secondary: "#eee8d5",
			secondaryForeground: "#657b83",
			muted: "#eee8d5",
			mutedForeground: "#93a1a1",
			accent: "#eee8d5",
			accentForeground: "#657b83",
			border: "#93a1a1",
			input: "#93a1a1",
			ring: "#268bd2",
			sidebar: "#eee8d5",
			sidebarForeground: "#657b83",
			sidebarPrimary: "#268bd2",
			sidebarPrimaryForeground: "#fdf6e3",
			sidebarAccent: "#fdf6e3",
			sidebarAccentForeground: "#657b83",
			sidebarBorder: "#93a1a1",
			folderColor: "#268bd2",
			// Toast - Solarized Style
			toastBackground: "#fdf6e3",
			toastForeground: "#657b83",
			toastBorder: "#93a1a1",
			editorSelection: "#d3cbb7",
		},
	},
	{
		key: "quiet-light",
		name: "Quiet Light",
		description: "柔和温暖的浅色主题",
		type: "light",
		colors: {
			background: "#f5f5f5",
			foreground: "#333333",
			card: "#ffffff",
			cardForeground: "#333333",
			popover: "#ffffff",
			popoverForeground: "#333333",
			primary: "#4078c0",
			primaryForeground: "#ffffff",
			secondary: "#e8e8e8",
			secondaryForeground: "#333333",
			muted: "#e8e8e8",
			mutedForeground: "#777777",
			accent: "#d3e8f8",
			accentForeground: "#333333",
			border: "#d4d4d4",
			input: "#d4d4d4",
			ring: "#4078c0",
			sidebar: "#f3f3f3",
			sidebarForeground: "#333333",
			sidebarPrimary: "#4078c0",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#d3e8f8",
			sidebarAccentForeground: "#333333",
			sidebarBorder: "#d4d4d4",
			folderColor: "#4078c0",
			// 扩展颜色
			editorCursor: "#4078c0",
			editorSelection: "#c8ddf0",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#333333",
			toastBorder: "#d4d4d4",
			editorLineHighlight: "#f0f0f0",
			success: "#22863a",
			warning: "#b08800",
			error: "#d73a49",
			info: "#4078c0",
			syntaxHeading: "#005cc5",
			syntaxBold: "#24292e",
			syntaxItalic: "#6a737d",
			syntaxLink: "#0366d6",
			syntaxCode: "#d73a49",
			syntaxQuote: "#6a737d",
			syntaxComment: "#6a737d",
		},
	},
	{
		key: "light-plus",
		name: "Light+",
		description: "VSCode 默认浅色主题",
		type: "light",
		colors: {
			background: "#ffffff",
			foreground: "#000000",
			card: "#ffffff",
			cardForeground: "#000000",
			popover: "#ffffff",
			popoverForeground: "#000000",
			primary: "#0066bf",
			primaryForeground: "#ffffff",
			secondary: "#f3f3f3",
			secondaryForeground: "#000000",
			muted: "#f3f3f3",
			mutedForeground: "#6a737d",
			accent: "#e8f2ff",
			accentForeground: "#000000",
			border: "#e5e5e5",
			input: "#e5e5e5",
			ring: "#0066bf",
			sidebar: "#f3f3f3",
			sidebarForeground: "#000000",
			sidebarPrimary: "#0066bf",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e8f2ff",
			sidebarAccentForeground: "#000000",
			sidebarBorder: "#e5e5e5",
			folderColor: "#0066bf",
			editorSelection: "#add6ff",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#000000",
			toastBorder: "#e5e5e5",
		},
	},
	{
		key: "atom-one-light",
		name: "Atom One Light",
		description: "流行的 Atom 浅色主题",
		type: "light",
		colors: {
			background: "#fafafa",
			foreground: "#383a42",
			card: "#ffffff",
			cardForeground: "#383a42",
			popover: "#ffffff",
			popoverForeground: "#383a42",
			primary: "#4078f2",
			primaryForeground: "#ffffff",
			secondary: "#f0f0f0",
			secondaryForeground: "#383a42",
			muted: "#f0f0f0",
			mutedForeground: "#a0a1a7",
			accent: "#e5f0ff",
			accentForeground: "#383a42",
			border: "#e5e5e6",
			input: "#e5e5e6",
			ring: "#4078f2",
			sidebar: "#f0f0f0",
			sidebarForeground: "#383a42",
			sidebarPrimary: "#4078f2",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e5f0ff",
			sidebarAccentForeground: "#383a42",
			sidebarBorder: "#e5e5e6",
			folderColor: "#4078f2",
			editorSelection: "#c9d0e5",
			// Toast
			toastBackground: "#fafafa",
			toastForeground: "#383a42",
			toastBorder: "#e5e5e6",
		},
	},
	{
		key: "winter-light",
		name: "Winter is Coming (Light)",
		description: "清新的蓝色调浅色主题",
		type: "light",
		colors: {
			background: "#ffffff",
			foreground: "#0e293f",
			card: "#ffffff",
			cardForeground: "#0e293f",
			popover: "#ffffff",
			popoverForeground: "#0e293f",
			primary: "#0073a1",
			primaryForeground: "#ffffff",
			secondary: "#f7f9fb",
			secondaryForeground: "#0e293f",
			muted: "#f7f9fb",
			mutedForeground: "#5a7a8c",
			accent: "#e3f2fd",
			accentForeground: "#0e293f",
			border: "#d9e7f1",
			input: "#d9e7f1",
			ring: "#0073a1",
			sidebar: "#f7f9fb",
			sidebarForeground: "#0e293f",
			sidebarPrimary: "#0073a1",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e3f2fd",
			sidebarAccentForeground: "#0e293f",
			sidebarBorder: "#d9e7f1",
			folderColor: "#0073a1",
			editorSelection: "#b3d7f0",
			// Toast
			toastBackground: "#f7f9fb",
			toastForeground: "#0e293f",
			toastBorder: "#d9e7f1",
		},
	},
	{
		key: "ayu-light",
		name: "Ayu Light",
		description: "现代简约的浅色主题",
		type: "light",
		colors: {
			background: "#fafafa",
			foreground: "#5c6166",
			card: "#ffffff",
			cardForeground: "#5c6166",
			popover: "#ffffff",
			popoverForeground: "#5c6166",
			primary: "#399ee6",
			primaryForeground: "#ffffff",
			secondary: "#f3f4f5",
			secondaryForeground: "#5c6166",
			muted: "#f3f4f5",
			mutedForeground: "#828c99",
			accent: "#e7f3fa",
			accentForeground: "#5c6166",
			border: "#e7e8e9",
			input: "#e7e8e9",
			ring: "#399ee6",
			sidebar: "#f8f9fa",
			sidebarForeground: "#5c6166",
			sidebarPrimary: "#399ee6",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e7f3fa",
			sidebarAccentForeground: "#5c6166",
			sidebarBorder: "#e7e8e9",
			folderColor: "#399ee6",
			editorSelection: "#c8e4f8",
			// Toast
			toastBackground: "#fafafa",
			toastForeground: "#5c6166",
			toastBorder: "#e7e8e9",
		},
	},
	{
		key: "gruvbox-light",
		name: "Gruvbox Light",
		description: "复古温暖浅色主题",
		type: "light",
		colors: {
			background: "#fbf1c7",
			foreground: "#3c3836",
			card: "#f9f5d7",
			cardForeground: "#3c3836",
			popover: "#f9f5d7",
			popoverForeground: "#3c3836",
			primary: "#076678",
			primaryForeground: "#fbf1c7",
			secondary: "#ebdbb2",
			secondaryForeground: "#3c3836",
			muted: "#ebdbb2",
			mutedForeground: "#7c6f64",
			accent: "#d5c4a1",
			accentForeground: "#3c3836",
			border: "#d5c4a1",
			input: "#d5c4a1",
			ring: "#076678",
			sidebar: "#f2e5bc",
			sidebarForeground: "#3c3836",
			sidebarPrimary: "#076678",
			sidebarPrimaryForeground: "#fbf1c7",
			sidebarAccent: "#d5c4a1",
			sidebarAccentForeground: "#3c3836",
			sidebarBorder: "#d5c4a1",
			folderColor: "#d79921",
			// Toast - Retro Style
			toastBackground: "#fbf1c7",
			toastBorder: "#d79921",
			editorSelection: "#d5c4a1",
		},
	},
	{
		key: "paper-light",
		name: "Paper",
		description: "Warm paper-like theme for comfortable reading",
		type: "light",
		colors: {
			background: "#f8f5f0",
			foreground: "#2c2c2c",
			card: "#ffffff",
			cardForeground: "#2c2c2c",
			popover: "#ffffff",
			popoverForeground: "#2c2c2c",
			primary: "#8b7355",
			primaryForeground: "#ffffff",
			secondary: "#f0ebe3",
			secondaryForeground: "#2c2c2c",
			muted: "#f0ebe3",
			mutedForeground: "#6b6b6b",
			accent: "#e8e0d5",
			accentForeground: "#2c2c2c",
			border: "#ddd5c8",
			input: "#ddd5c8",
			ring: "#8b7355",
			sidebar: "#f5f0e8",
			sidebarForeground: "#2c2c2c",
			sidebarPrimary: "#8b7355",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e8e0d5",
			sidebarAccentForeground: "#2c2c2c",
			sidebarBorder: "#ddd5c8",
			folderColor: "#8b7355",
			// Toast - Warm Paper Style
			toastBackground: "#fff9f0",
			toastForeground: "#2c2c2c",
			toastBorder: "#e8e0d5",
			editorSelection: "#d4c4a8",
		},
	},
	{
		key: "sepia",
		name: "Sepia",
		description: "Classic sepia tone for reduced eye strain",
		type: "light",
		colors: {
			background: "#f4ecd8",
			foreground: "#5b4636",
			card: "#faf6eb",
			cardForeground: "#5b4636",
			popover: "#faf6eb",
			popoverForeground: "#5b4636",
			primary: "#8b6914",
			primaryForeground: "#ffffff",
			secondary: "#ebe3d0",
			secondaryForeground: "#5b4636",
			muted: "#ebe3d0",
			mutedForeground: "#7a6a5a",
			accent: "#e0d5be",
			accentForeground: "#5b4636",
			border: "#d4c9b0",
			input: "#d4c9b0",
			ring: "#8b6914",
			sidebar: "#f0e8d5",
			sidebarForeground: "#5b4636",
			sidebarPrimary: "#8b6914",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e0d5be",
			sidebarAccentForeground: "#5b4636",
			sidebarBorder: "#d4c9b0",
			folderColor: "#8b6914",
			editorSelection: "#d4c4a0",
			// Toast
			toastBackground: "#f4ecd8",
			toastForeground: "#5b4636",
			toastBorder: "#d4c9b0",
		},
	},
	{
		key: "nord-light",
		name: "Nord Light",
		description: "Cool Nordic-inspired light theme",
		type: "light",
		colors: {
			background: "#eceff4",
			foreground: "#2e3440",
			card: "#ffffff",
			cardForeground: "#2e3440",
			popover: "#ffffff",
			popoverForeground: "#2e3440",
			primary: "#5e81ac",
			primaryForeground: "#ffffff",
			secondary: "#e5e9f0",
			secondaryForeground: "#2e3440",
			muted: "#e5e9f0",
			mutedForeground: "#4c566a",
			accent: "#d8dee9",
			accentForeground: "#2e3440",
			border: "#d8dee9",
			input: "#d8dee9",
			ring: "#5e81ac",
			sidebar: "#e5e9f0",
			sidebarForeground: "#2e3440",
			sidebarPrimary: "#5e81ac",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#d8dee9",
			sidebarAccentForeground: "#2e3440",
			sidebarBorder: "#d8dee9",
			folderColor: "#88c0d0",
			editorSelection: "#b8c5d9",
			// Toast
			toastBackground: "#eceff4",
			toastForeground: "#2e3440",
			toastBorder: "#d8dee9",
		},
	},
	{
		key: "rose-pine-dawn",
		name: "Rosé Pine Dawn",
		description: "Soothing pastel light theme",
		type: "light",
		colors: {
			background: "#faf4ed",
			foreground: "#575279",
			card: "#fffaf3",
			cardForeground: "#575279",
			popover: "#fffaf3",
			popoverForeground: "#575279",
			primary: "#d7827e",
			primaryForeground: "#faf4ed",
			secondary: "#f2e9e1",
			secondaryForeground: "#575279",
			muted: "#f2e9e1",
			mutedForeground: "#9893a5",
			accent: "#f2e9e1",
			accentForeground: "#575279",
			border: "#dfdad9",
			input: "#dfdad9",
			ring: "#d7827e",
			sidebar: "#f2e9e1",
			sidebarForeground: "#575279",
			sidebarPrimary: "#d7827e",
			sidebarPrimaryForeground: "#faf4ed",
			sidebarAccent: "#fffaf3",
			sidebarAccentForeground: "#575279",
			sidebarBorder: "#dfdad9",
			folderColor: "#ea9a97",
			editorSelection: "#dfdad9",
			// Toast
			toastBackground: "#faf4ed",
			toastForeground: "#575279",
			toastBorder: "#dfdad9",
		},
	},
	{
		key: "catppuccin-latte",
		name: "Catppuccin Latte",
		description: "Warm and soothing light theme",
		type: "light",
		colors: {
			background: "#eff1f5",
			foreground: "#4c4f69",
			card: "#e6e9ef",
			cardForeground: "#4c4f69",
			popover: "#e6e9ef",
			popoverForeground: "#4c4f69",
			primary: "#1e66f5",
			primaryForeground: "#eff1f5",
			secondary: "#ccd0da",
			secondaryForeground: "#4c4f69",
			muted: "#ccd0da",
			mutedForeground: "#9ca0b0",
			accent: "#e6e9ef",
			accentForeground: "#4c4f69",
			border: "#bcc0cc",
			input: "#bcc0cc",
			ring: "#1e66f5",
			sidebar: "#e6e9ef",
			sidebarForeground: "#4c4f69",
			sidebarPrimary: "#1e66f5",
			sidebarPrimaryForeground: "#eff1f5",
			sidebarAccent: "#dce0e8",
			sidebarAccentForeground: "#4c4f69",
			sidebarBorder: "#bcc0cc",
			folderColor: "#1e66f5",
			editorSelection: "#acb0be",
			// Toast
			toastBackground: "#eff1f5",
			toastForeground: "#4c4f69",
			toastBorder: "#bcc0cc",
		},
	},
	{
		key: "tokyo-night-day",
		name: "Tokyo Night Day",
		description: "Bright and colorful light theme",
		type: "light",
		colors: {
			background: "#e1e2e7",
			foreground: "#3760bf",
			card: "#d5d6db",
			cardForeground: "#3760bf",
			popover: "#d5d6db",
			popoverForeground: "#3760bf",
			primary: "#2e7de9",
			primaryForeground: "#e1e2e7",
			secondary: "#d0d5e3",
			secondaryForeground: "#3760bf",
			muted: "#d0d5e3",
			mutedForeground: "#848cb5",
			accent: "#d0d5e3",
			accentForeground: "#3760bf",
			border: "#9aa5ce",
			input: "#9aa5ce",
			ring: "#2e7de9",
			sidebar: "#d5d6db",
			sidebarForeground: "#3760bf",
			sidebarPrimary: "#2e7de9",
			sidebarPrimaryForeground: "#e1e2e7",
			sidebarAccent: "#c4c8da",
			sidebarAccentForeground: "#3760bf",
			sidebarBorder: "#9aa5ce",
			folderColor: "#2e7de9",
			editorSelection: "#99a7df",
			// Toast
			toastBackground: "#e1e2e7",
			toastForeground: "#3760bf",
			toastBorder: "#9aa5ce",
		},
	},
	{
		key: "bluloco-light",
		name: "Bluloco Light",
		description: "Sophisticated blue light theme",
		type: "light",
		colors: {
			background: "#f9f9f9",
			foreground: "#383a42",
			card: "#ffffff",
			cardForeground: "#383a42",
			popover: "#ffffff",
			popoverForeground: "#383a42",
			primary: "#0098dd",
			primaryForeground: "#ffffff",
			secondary: "#f0f1f2",
			secondaryForeground: "#383a42",
			muted: "#f0f1f2",
			mutedForeground: "#a0a1a7",
			accent: "#e5f5fc",
			accentForeground: "#383a42",
			border: "#e5e6e7",
			input: "#e5e6e7",
			ring: "#0098dd",
			sidebar: "#f3f3f3",
			sidebarForeground: "#383a42",
			sidebarPrimary: "#0098dd",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e5f5fc",
			sidebarAccentForeground: "#383a42",
			sidebarBorder: "#e5e6e7",
			folderColor: "#0098dd",
			editorSelection: "#cceae7",
			// Toast
			toastBackground: "#f9f9f9",
			toastForeground: "#383a42",
			toastBorder: "#e5e6e7",
		},
	},
	{
		key: "everforest-light",
		name: "Everforest Light",
		description: "Natural and comfortable light theme",
		type: "light",
		colors: {
			background: "#fdf6e3",
			foreground: "#5c6a72",
			card: "#f3efda",
			cardForeground: "#5c6a72",
			popover: "#f3efda",
			popoverForeground: "#5c6a72",
			primary: "#8da101",
			primaryForeground: "#fdf6e3",
			secondary: "#efebd4",
			secondaryForeground: "#5c6a72",
			muted: "#efebd4",
			mutedForeground: "#939f91",
			accent: "#e9e5cf",
			accentForeground: "#5c6a72",
			border: "#e0dcc7",
			input: "#e0dcc7",
			ring: "#8da101",
			sidebar: "#f8f5e4",
			sidebarForeground: "#5c6a72",
			sidebarPrimary: "#8da101",
			sidebarPrimaryForeground: "#fdf6e3",
			sidebarAccent: "#e9e5cf",
			sidebarAccentForeground: "#5c6a72",
			sidebarBorder: "#e0dcc7",
			folderColor: "#8da101",
			editorSelection: "#e9e5cf",
			// Toast
			toastBackground: "#fdf6e3",
			toastForeground: "#5c6a72",
			toastBorder: "#e0dcc7",
		},
	},
	{
		key: "dawn",
		name: "Dawn",
		description: "柔和的黎明主题",
		type: "light",
		colors: {
			background: "#F9F9F9",
			foreground: "#080808",
			card: "#F9F9F9",
			cardForeground: "#080808",
			popover: "#F9F9F9",
			popoverForeground: "#080808",
			primary: "#B45A3C",
			primaryForeground: "#FFFFFF",
			secondary: "#EFF2F5",
			secondaryForeground: "#080808",
			muted: "#EFF2F5",
			mutedForeground: "#586069",
			accent: "#EAEAEB",
			accentForeground: "#080808",
			border: "#D7D7D7",
			input: "#D7D7D7",
			ring: "#B45A3C",
			sidebar: "#F5F5F5",
			sidebarForeground: "#080808",
			sidebarPrimary: "#B45A3C",
			sidebarPrimaryForeground: "#FFFFFF",
			sidebarAccent: "#EAEAEB",
			sidebarAccentForeground: "#080808",
			sidebarBorder: "#D7D7D7",
			folderColor: "#B45A3C",
			editorSelection: "#EAEAEB",
			// Toast
			toastBackground: "#F9F9F9",
			toastForeground: "#080808",
			toastBorder: "#D7D7D7",
		},
	},
	{
		key: "min-light",
		name: "Min Light",
		description: "极简纯白主题",
		type: "light",
		colors: {
			background: "#ffffff",
			foreground: "#111111",
			card: "#ffffff",
			cardForeground: "#111111",
			popover: "#ffffff",
			popoverForeground: "#111111",
			primary: "#111111",
			primaryForeground: "#ffffff",
			secondary: "#f5f5f5",
			secondaryForeground: "#111111",
			muted: "#f5f5f5",
			mutedForeground: "#888888",
			accent: "#f5f5f5",
			accentForeground: "#111111",
			border: "#eaeaea",
			input: "#eaeaea",
			ring: "#111111",
			sidebar: "#ffffff",
			sidebarForeground: "#111111",
			sidebarPrimary: "#111111",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#f5f5f5",
			sidebarAccentForeground: "#111111",
			sidebarBorder: "#eaeaea",
			folderColor: "#111111",
			editorSelection: "#eeeeee",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#111111",
			toastBorder: "#eaeaea",
		},
	},
	{
		key: "flat-light",
		name: "Flat Light",
		description: "扁平化清爽主题",
		type: "light",
		colors: {
			background: "#f2f2f2",
			foreground: "#2c3e50",
			card: "#ffffff",
			cardForeground: "#2c3e50",
			popover: "#ffffff",
			popoverForeground: "#2c3e50",
			primary: "#3498db",
			primaryForeground: "#ffffff",
			secondary: "#e0e0e0",
			secondaryForeground: "#2c3e50",
			muted: "#e0e0e0",
			mutedForeground: "#7f8c8d",
			accent: "#ecf0f1",
			accentForeground: "#2c3e50",
			border: "#bdc3c7",
			input: "#bdc3c7",
			ring: "#3498db",
			sidebar: "#ecf0f1",
			sidebarForeground: "#2c3e50",
			sidebarPrimary: "#3498db",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e0e0e0",
			sidebarAccentForeground: "#2c3e50",
			sidebarBorder: "#bdc3c7",
			folderColor: "#3498db",
			editorSelection: "#d5dbdb",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#2c3e50",
			toastBorder: "#bdc3c7",
		},
	},
	{
		key: "vitesse-light",
		name: "Vitesse Light",
		description: "温暖的淡黄色主题",
		type: "light",
		colors: {
			background: "#ffffff",
			foreground: "#3d3d3d",
			card: "#ffffff",
			cardForeground: "#3d3d3d",
			popover: "#ffffff",
			popoverForeground: "#3d3d3d",
			primary: "#646cff",
			primaryForeground: "#ffffff",
			secondary: "#f9f9f9",
			secondaryForeground: "#3d3d3d",
			muted: "#f9f9f9",
			mutedForeground: "#8e8e8e",
			accent: "#f1f1f1",
			accentForeground: "#3d3d3d",
			border: "#e5e5e5",
			input: "#e5e5e5",
			ring: "#646cff",
			sidebar: "#f9f9f9",
			sidebarForeground: "#3d3d3d",
			sidebarPrimary: "#646cff",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#e5e5e5",
			sidebarAccentForeground: "#3d3d3d",
			sidebarBorder: "#e5e5e5",
			folderColor: "#646cff",
			editorSelection: "#dbeafe",
			// Toast
			toastBackground: "#ffffff",
			toastForeground: "#3d3d3d",
			toastBorder: "#e5e5e5",
		},
	},
	{
		key: "summer",
		name: "Summer",
		description: "夏日明亮主题",
		type: "light",
		colors: {
			background: "#fefdf5",
			foreground: "#4a4a4a",
			card: "#ffffff",
			cardForeground: "#4a4a4a",
			popover: "#ffffff",
			popoverForeground: "#4a4a4a",
			primary: "#ff6b6b",
			primaryForeground: "#ffffff",
			secondary: "#fdf6e3",
			secondaryForeground: "#4a4a4a",
			muted: "#fdf6e3",
			mutedForeground: "#999999",
			accent: "#ffe3e3",
			accentForeground: "#4a4a4a",
			border: "#e6e6e6",
			input: "#e6e6e6",
			ring: "#ff6b6b",
			sidebar: "#fff9f0",
			sidebarForeground: "#4a4a4a",
			sidebarPrimary: "#ff6b6b",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#ffe3e3",
			sidebarAccentForeground: "#4a4a4a",
			sidebarBorder: "#f0e0d0",
			folderColor: "#ff6b6b",
			// Toast - Summer Pop
			toastBackground: "#fff9f0",
			toastBorder: "#ff6b6b",
			editorSelection: "#fff0f0",
		},
	},
	// ============ 深色主题 ============
	{
		key: "default-dark",
		name: "Default Dark",
		description: "默认深色主题",
		type: "dark",
		colors: {
			background: "#0f172a",
			foreground: "#f1f5f9",
			card: "#1e293b",
			cardForeground: "#f1f5f9",
			popover: "#1e293b",
			popoverForeground: "#f1f5f9",
			primary: "#3b82f6",
			primaryForeground: "#ffffff",
			secondary: "#1e293b",
			secondaryForeground: "#f1f5f9",
			muted: "#334155",
			mutedForeground: "#94a3b8",
			accent: "#1e3a5f",
			accentForeground: "#f1f5f9",
			border: "#334155",
			input: "#334155",
			ring: "#3b82f6",
			sidebar: "#0f172a",
			sidebarForeground: "#f1f5f9",
			sidebarPrimary: "#3b82f6",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#1e3a5f",
			sidebarAccentForeground: "#f1f5f9",
			sidebarBorder: "#334155",
			folderColor: "#3b82f6",
			// 编辑器扩展颜色
			editorCursor: "#60a5fa",
			editorSelection: "#1e3a5f",
			// Toast
			toastBackground: "#1e293b",
			toastForeground: "#f1f5f9",
			toastBorder: "#334155",
			editorLineHighlight: "#1e293b",
		},
	},
	{
		key: "github-dark",
		name: "GitHub Dark",
		description: "GitHub 深色主题",
		type: "dark",
		colors: {
			background: "#0d1117",
			foreground: "#c9d1d9",
			card: "#161b22",
			cardForeground: "#c9d1d9",
			popover: "#161b22",
			popoverForeground: "#c9d1d9",
			primary: "#58a6ff",
			primaryForeground: "#0d1117",
			secondary: "#21262d",
			secondaryForeground: "#c9d1d9",
			muted: "#21262d",
			mutedForeground: "#8b949e",
			accent: "#1f6feb33",
			accentForeground: "#c9d1d9",
			border: "#30363d",
			input: "#30363d",
			ring: "#58a6ff",
			sidebar: "#010409",
			sidebarForeground: "#c9d1d9",
			sidebarPrimary: "#58a6ff",
			sidebarPrimaryForeground: "#0d1117",
			sidebarAccent: "#1f6feb33",
			sidebarAccentForeground: "#c9d1d9",
			sidebarBorder: "#30363d",
			folderColor: "#58a6ff",
			// 编辑器扩展颜色
			editorCursor: "#58a6ff",
			editorSelection: "#264f78",
			// Toast
			toastBackground: "#161b22",
			toastForeground: "#c9d1d9",
			toastBorder: "#30363d",
			editorLineHighlight: "#161b22",
		},
	},
	{
		key: "one-dark-pro",
		name: "One Dark Pro",
		description: "经典 Atom 深色主题",
		type: "dark",
		colors: {
			background: "#282c34",
			foreground: "#abb2bf",
			card: "#21252b",
			cardForeground: "#abb2bf",
			popover: "#21252b",
			popoverForeground: "#abb2bf",
			primary: "#61afef",
			primaryForeground: "#282c34",
			secondary: "#3e4451",
			secondaryForeground: "#abb2bf",
			muted: "#3e4451",
			mutedForeground: "#5c6370",
			accent: "#2c313a",
			accentForeground: "#abb2bf",
			border: "#3e4451",
			input: "#3e4451",
			ring: "#61afef",
			sidebar: "#21252b",
			sidebarForeground: "#abb2bf",
			sidebarPrimary: "#61afef",
			sidebarPrimaryForeground: "#282c34",
			sidebarAccent: "#2c313a",
			sidebarAccentForeground: "#abb2bf",
			sidebarBorder: "#3e4451",
			folderColor: "#61afef",
			// 编辑器扩展颜色
			editorCursor: "#528bff",
			editorSelection: "#3e4451",
			// Toast
			toastBackground: "#282c34",
			toastForeground: "#abb2bf",
			toastBorder: "#3e4451",
			editorLineHighlight: "#2c313c",
		},
	},
	{
		key: "dracula",
		name: "Dracula",
		description: "吸血鬼紫色主题",
		type: "dark",
		colors: {
			background: "#282a36",
			foreground: "#f8f8f2",
			card: "#21222c",
			cardForeground: "#f8f8f2",
			popover: "#21222c",
			popoverForeground: "#f8f8f2",
			primary: "#bd93f9",
			primaryForeground: "#282a36",
			secondary: "#44475a",
			secondaryForeground: "#f8f8f2",
			muted: "#44475a",
			mutedForeground: "#6272a4",
			accent: "#44475a",
			accentForeground: "#f8f8f2",
			border: "#44475a",
			input: "#44475a",
			ring: "#bd93f9",
			sidebar: "#21222c",
			sidebarForeground: "#f8f8f2",
			sidebarPrimary: "#bd93f9",
			sidebarPrimaryForeground: "#282a36",
			sidebarAccent: "#44475a",
			sidebarAccentForeground: "#f8f8f2",
			sidebarBorder: "#44475a",
			folderColor: "#bd93f9",
			// Toast - Dracula Style
			toastBackground: "#282a36",
			toastForeground: "#f8f8f2",
			toastBorder: "#bd93f9",
			// 扩展颜色
			editorCursor: "#f8f8f0",
			editorSelection: "#44475a",
			editorLineHighlight: "#44475a",
			success: "#50fa7b",
			warning: "#f1fa8c",
			error: "#ff5555",
			info: "#8be9fd",
			syntaxHeading: "#bd93f9",
			syntaxBold: "#f8f8f2",
			syntaxItalic: "#f1fa8c",
			syntaxLink: "#8be9fd",
			syntaxCode: "#ff79c6",
			syntaxQuote: "#6272a4",
			syntaxComment: "#6272a4",
		},
	},
	{
		key: "nord",
		name: "Nord",
		description: "北欧冷色调主题",
		type: "dark",
		colors: {
			background: "#2e3440",
			foreground: "#eceff4",
			card: "#3b4252",
			cardForeground: "#eceff4",
			popover: "#3b4252",
			popoverForeground: "#eceff4",
			primary: "#88c0d0",
			primaryForeground: "#2e3440",
			secondary: "#3b4252",
			secondaryForeground: "#eceff4",
			muted: "#434c5e",
			mutedForeground: "#d8dee9",
			accent: "#434c5e",
			accentForeground: "#eceff4",
			border: "#4c566a",
			input: "#4c566a",
			ring: "#88c0d0",
			sidebar: "#2e3440",
			sidebarForeground: "#eceff4",
			sidebarPrimary: "#88c0d0",
			sidebarPrimaryForeground: "#2e3440",
			sidebarAccent: "#434c5e",
			sidebarAccentForeground: "#eceff4",
			sidebarBorder: "#4c566a",
			folderColor: "#88c0d0",
			// Toast - Frost Style
			toastBackground: "#3b4252",
			toastBorder: "#88c0d0",
			// 编辑器扩展颜色
			editorCursor: "#d8dee9",
			editorSelection: "#434c5e",
			editorLineHighlight: "#3b4252",
		},
	},
	{
		key: "monokai-pro",
		name: "Monokai Pro",
		description: "经典 Monokai 主题",
		type: "dark",
		colors: {
			background: "#2d2a2e",
			foreground: "#fcfcfa",
			card: "#221f22",
			cardForeground: "#fcfcfa",
			popover: "#221f22",
			popoverForeground: "#fcfcfa",
			primary: "#ffd866",
			primaryForeground: "#2d2a2e",
			secondary: "#403e41",
			secondaryForeground: "#fcfcfa",
			muted: "#403e41",
			mutedForeground: "#939293",
			accent: "#403e41",
			accentForeground: "#fcfcfa",
			border: "#5b595c",
			input: "#5b595c",
			ring: "#ffd866",
			sidebar: "#221f22",
			sidebarForeground: "#fcfcfa",
			sidebarPrimary: "#ffd866",
			sidebarPrimaryForeground: "#2d2a2e",
			sidebarAccent: "#403e41",
			sidebarAccentForeground: "#fcfcfa",
			sidebarBorder: "#5b595c",
			folderColor: "#ffd866",
			editorSelection: "#544f4f",
			// Toast
			toastBackground: "#2d2a2e",
			toastForeground: "#fcfcfa",
			toastBorder: "#5b595c",
		},
	},
	{
		key: "solarized-dark",
		name: "Solarized Dark",
		description: "护眼深色主题",
		type: "dark",
		colors: {
			background: "#002b36",
			foreground: "#839496",
			card: "#073642",
			cardForeground: "#839496",
			popover: "#073642",
			popoverForeground: "#839496",
			primary: "#268bd2",
			primaryForeground: "#fdf6e3",
			secondary: "#073642",
			secondaryForeground: "#839496",
			muted: "#073642",
			mutedForeground: "#586e75",
			accent: "#073642",
			accentForeground: "#839496",
			border: "#586e75",
			input: "#586e75",
			ring: "#268bd2",
			sidebar: "#002b36",
			sidebarForeground: "#839496",
			sidebarPrimary: "#268bd2",
			sidebarPrimaryForeground: "#fdf6e3",
			sidebarAccent: "#073642",
			sidebarAccentForeground: "#839496",
			sidebarBorder: "#586e75",
			folderColor: "#268bd2",
			editorSelection: "#094959",
			// Toast
			toastBackground: "#002b36",
			toastForeground: "#839496",
			toastBorder: "#586e75",
		},
	},
	{
		key: "tokyo-night",
		name: "Tokyo Night",
		description: "流行的深蓝紫色主题",
		type: "dark",
		colors: {
			background: "#1a1b26",
			foreground: "#a9b1d6",
			card: "#16161e",
			cardForeground: "#a9b1d6",
			popover: "#16161e",
			popoverForeground: "#a9b1d6",
			primary: "#7aa2f7",
			primaryForeground: "#1a1b26",
			secondary: "#24283b",
			secondaryForeground: "#a9b1d6",
			muted: "#24283b",
			mutedForeground: "#565f89",
			accent: "#292e42",
			accentForeground: "#a9b1d6",
			border: "#414868",
			input: "#414868",
			ring: "#7aa2f7",
			sidebar: "#16161e",
			sidebarForeground: "#a9b1d6",
			sidebarPrimary: "#7aa2f7",
			sidebarPrimaryForeground: "#1a1b26",
			sidebarAccent: "#292e42",
			sidebarAccentForeground: "#a9b1d6",
			sidebarBorder: "#414868",
			folderColor: "#7aa2f7",
			// 扩展颜色
			editorCursor: "#c0caf5",
			editorSelection: "#364a82",
			// Toast
			toastBackground: "#1a1b26",
			toastForeground: "#a9b1d6",
			toastBorder: "#414868",
			editorLineHighlight: "#1f2335",
			success: "#9ece6a",
			warning: "#e0af68",
			error: "#f7768e",
			info: "#7aa2f7",
			syntaxHeading: "#bb9af7",
			syntaxBold: "#c0caf5",
			syntaxItalic: "#7dcfff",
			syntaxLink: "#7aa2f7",
			syntaxCode: "#ff9e64",
			syntaxQuote: "#565f89",
			syntaxComment: "#565f89",
		},
	},
	{
		key: "material-ocean",
		name: "Material Theme Ocean",
		description: "优雅的海洋蓝主题",
		type: "dark",
		colors: {
			background: "#0f111a",
			foreground: "#8f93a2",
			card: "#090b10",
			cardForeground: "#8f93a2",
			popover: "#090b10",
			popoverForeground: "#8f93a2",
			primary: "#82aaff",
			primaryForeground: "#0f111a",
			secondary: "#1e2030",
			secondaryForeground: "#8f93a2",
			muted: "#1e2030",
			mutedForeground: "#464b5d",
			accent: "#1e2030",
			accentForeground: "#8f93a2",
			border: "#464b5d",
			input: "#464b5d",
			ring: "#82aaff",
			sidebar: "#090b10",
			sidebarForeground: "#8f93a2",
			sidebarPrimary: "#82aaff",
			sidebarPrimaryForeground: "#0f111a",
			sidebarAccent: "#1e2030",
			sidebarAccentForeground: "#8f93a2",
			sidebarBorder: "#464b5d",
			folderColor: "#82aaff",
			editorSelection: "#2b3245",
			// Toast
			toastBackground: "#090b10",
			toastForeground: "#8f93a2",
			toastBorder: "#464b5d",
		},
	},
	{
		key: "palenight",
		name: "Palenight",
		description: "柔和的紫色深色主题",
		type: "dark",
		colors: {
			background: "#292d3e",
			foreground: "#a6accd",
			card: "#1f2233",
			cardForeground: "#a6accd",
			popover: "#1f2233",
			popoverForeground: "#a6accd",
			primary: "#82aaff",
			primaryForeground: "#292d3e",
			secondary: "#3a3f58",
			secondaryForeground: "#a6accd",
			muted: "#3a3f58",
			mutedForeground: "#676e95",
			accent: "#3a3f58",
			accentForeground: "#a6accd",
			border: "#4e5579",
			input: "#4e5579",
			ring: "#82aaff",
			sidebar: "#1f2233",
			sidebarForeground: "#a6accd",
			sidebarPrimary: "#82aaff",
			sidebarPrimaryForeground: "#292d3e",
			sidebarAccent: "#3a3f58",
			sidebarAccentForeground: "#a6accd",
			sidebarBorder: "#4e5579",
			folderColor: "#c792ea",
			editorSelection: "#3e4460",
			// Toast
			toastBackground: "#292d3e",
			toastForeground: "#a6accd",
			toastBorder: "#4e5579",
		},
	},
	{
		key: "gruvbox-dark",
		name: "Gruvbox Dark",
		description: "复古温暖深色主题",
		type: "dark",
		colors: {
			background: "#282828",
			foreground: "#ebdbb2",
			card: "#1d2021",
			cardForeground: "#ebdbb2",
			popover: "#1d2021",
			popoverForeground: "#ebdbb2",
			primary: "#83a598",
			primaryForeground: "#282828",
			secondary: "#3c3836",
			secondaryForeground: "#ebdbb2",
			muted: "#3c3836",
			mutedForeground: "#a89984",
			accent: "#504945",
			accentForeground: "#ebdbb2",
			border: "#504945",
			input: "#504945",
			ring: "#83a598",
			sidebar: "#1d2021",
			sidebarForeground: "#ebdbb2",
			sidebarPrimary: "#83a598",
			sidebarPrimaryForeground: "#282828",
			sidebarAccent: "#504945",
			sidebarAccentForeground: "#ebdbb2",
			sidebarBorder: "#504945",
			folderColor: "#d79921",
			editorSelection: "#504945",
			// Toast
			toastBackground: "#282828",
			toastForeground: "#ebdbb2",
			toastBorder: "#504945",
		},
	},
	{
		key: "night-owl",
		name: "Night Owl",
		description: "夜猫子深色主题",
		type: "dark",
		colors: {
			background: "#011627",
			foreground: "#d6deeb",
			card: "#01111d",
			cardForeground: "#d6deeb",
			popover: "#01111d",
			popoverForeground: "#d6deeb",
			primary: "#82aaff",
			primaryForeground: "#011627",
			secondary: "#0b2942",
			secondaryForeground: "#d6deeb",
			muted: "#0b2942",
			mutedForeground: "#637777",
			accent: "#1d3b53",
			accentForeground: "#d6deeb",
			border: "#1d3b53",
			input: "#1d3b53",
			ring: "#82aaff",
			sidebar: "#011627",
			sidebarForeground: "#d6deeb",
			sidebarPrimary: "#82aaff",
			sidebarPrimaryForeground: "#011627",
			sidebarAccent: "#1d3b53",
			sidebarAccentForeground: "#d6deeb",
			sidebarBorder: "#1d3b53",
			folderColor: "#82aaff",
			editorSelection: "#1d3b53",
		},
	},
	{
		key: "cobalt2",
		name: "Cobalt2",
		description: "鲜艳的蓝色主题",
		type: "dark",
		colors: {
			background: "#193549",
			foreground: "#ffffff",
			card: "#122738",
			cardForeground: "#ffffff",
			popover: "#122738",
			popoverForeground: "#ffffff",
			primary: "#ffc600",
			primaryForeground: "#193549",
			secondary: "#1f4662",
			secondaryForeground: "#ffffff",
			muted: "#1f4662",
			mutedForeground: "#0088ff",
			accent: "#1f4662",
			accentForeground: "#ffffff",
			border: "#0d3a58",
			input: "#0d3a58",
			ring: "#ffc600",
			sidebar: "#15232d",
			sidebarForeground: "#ffffff",
			sidebarPrimary: "#ffc600",
			sidebarPrimaryForeground: "#193549",
			sidebarAccent: "#1f4662",
			sidebarAccentForeground: "#ffffff",
			sidebarBorder: "#0d3a58",
			folderColor: "#ffc600",
			editorSelection: "#1f4662",
			// Toast
			toastBackground: "#193549",
			toastForeground: "#ffffff",
			toastBorder: "#0d3a58",
		},
	},
	{
		key: "synthwave-84",
		name: "SynthWave '84",
		description: "赛博朋克霓虹主题",
		type: "dark",
		colors: {
			background: "#262335",
			foreground: "#f92aad",
			card: "#1e1b2e",
			cardForeground: "#f92aad",
			popover: "#1e1b2e",
			popoverForeground: "#f92aad",
			primary: "#ff7edb",
			primaryForeground: "#262335",
			secondary: "#2a2139",
			secondaryForeground: "#f92aad",
			muted: "#2a2139",
			mutedForeground: "#848bbd",
			accent: "#34294f",
			accentForeground: "#f92aad",
			border: "#495495",
			input: "#495495",
			ring: "#ff7edb",
			sidebar: "#241b2f",
			sidebarForeground: "#f92aad",
			sidebarPrimary: "#ff7edb",
			sidebarPrimaryForeground: "#262335",
			sidebarAccent: "#34294f",
			sidebarAccentForeground: "#f92aad",
			sidebarBorder: "#495495",
			folderColor: "#ff7edb",
			editorSelection: "#463465",
			// Toast
			toastBackground: "#262335",
			toastForeground: "#f92aad",
			toastBorder: "#495495",
		},
	},
	{
		key: "shades-of-purple",
		name: "Shades of Purple",
		description: "紫色渐变主题",
		type: "dark",
		colors: {
			background: "#2d2b55",
			foreground: "#ffffff",
			card: "#1e1e3f",
			cardForeground: "#ffffff",
			popover: "#1e1e3f",
			popoverForeground: "#ffffff",
			primary: "#fad000",
			primaryForeground: "#2d2b55",
			secondary: "#4d21fc",
			secondaryForeground: "#ffffff",
			muted: "#4d21fc",
			mutedForeground: "#a599e9",
			accent: "#4d21fc",
			accentForeground: "#ffffff",
			border: "#7c4dff",
			input: "#7c4dff",
			ring: "#fad000",
			sidebar: "#1e1e3f",
			sidebarForeground: "#ffffff",
			sidebarPrimary: "#fad000",
			sidebarPrimaryForeground: "#2d2b55",
			sidebarAccent: "#4d21fc",
			sidebarAccentForeground: "#ffffff",
			sidebarBorder: "#7c4dff",
			folderColor: "#fad000",
			editorSelection: "#5c4d9a",
			// Toast
			toastBackground: "#2d2b55",
			toastForeground: "#ffffff",
			toastBorder: "#7c4dff",
		},
	},
	{
		key: "winter-dark",
		name: "Winter is Coming (Dark)",
		description: "冬日深色主题",
		type: "dark",
		colors: {
			background: "#011627",
			foreground: "#d6deeb",
			card: "#001424",
			cardForeground: "#d6deeb",
			popover: "#001424",
			popoverForeground: "#d6deeb",
			primary: "#7fdbca",
			primaryForeground: "#011627",
			secondary: "#0b2942",
			secondaryForeground: "#d6deeb",
			muted: "#0b2942",
			mutedForeground: "#5f7e97",
			accent: "#1d3b53",
			accentForeground: "#d6deeb",
			border: "#1d3b53",
			input: "#1d3b53",
			ring: "#7fdbca",
			sidebar: "#011627",
			sidebarForeground: "#d6deeb",
			sidebarPrimary: "#7fdbca",
			sidebarPrimaryForeground: "#011627",
			sidebarAccent: "#1d3b53",
			sidebarAccentForeground: "#d6deeb",
			sidebarBorder: "#1d3b53",
			folderColor: "#7fdbca",
			editorSelection: "#1d3b53",
			// Toast
			toastBackground: "#011627",
			toastForeground: "#d6deeb",
			toastBorder: "#1d3b53",
		},
	},
	{
		key: "ayu-dark",
		name: "Ayu Dark",
		description: "现代简约深色主题",
		type: "dark",
		colors: {
			background: "#0a0e14",
			foreground: "#b3b1ad",
			card: "#01060e",
			cardForeground: "#b3b1ad",
			popover: "#01060e",
			popoverForeground: "#b3b1ad",
			primary: "#39bae6",
			primaryForeground: "#0a0e14",
			secondary: "#0d1016",
			secondaryForeground: "#b3b1ad",
			muted: "#0d1016",
			mutedForeground: "#626a73",
			accent: "#1f2430",
			accentForeground: "#b3b1ad",
			border: "#1f2430",
			input: "#1f2430",
			ring: "#39bae6",
			sidebar: "#01060e",
			sidebarForeground: "#b3b1ad",
			sidebarPrimary: "#39bae6",
			sidebarPrimaryForeground: "#0a0e14",
			sidebarAccent: "#1f2430",
			sidebarAccentForeground: "#b3b1ad",
			sidebarBorder: "#1f2430",
			folderColor: "#39bae6",
			editorSelection: "#273747",
			// Toast
			toastBackground: "#0a0e14",
			toastForeground: "#b3b1ad",
			toastBorder: "#1f2430",
		},
	},
	{
		key: "ayu-mirage",
		name: "Ayu Mirage",
		description: "Ayu 中间色调主题",
		type: "dark",
		colors: {
			background: "#1f2430",
			foreground: "#cbccc6",
			card: "#191e2a",
			cardForeground: "#cbccc6",
			popover: "#191e2a",
			popoverForeground: "#cbccc6",
			primary: "#5ccfe6",
			primaryForeground: "#1f2430",
			secondary: "#242936",
			secondaryForeground: "#cbccc6",
			muted: "#242936",
			mutedForeground: "#707a8c",
			accent: "#343d4a",
			accentForeground: "#cbccc6",
			border: "#343d4a",
			input: "#343d4a",
			ring: "#5ccfe6",
			sidebar: "#1f2430",
			sidebarForeground: "#cbccc6",
			sidebarPrimary: "#5ccfe6",
			sidebarPrimaryForeground: "#1f2430",
			sidebarAccent: "#343d4a",
			sidebarAccentForeground: "#cbccc6",
			sidebarBorder: "#343d4a",
			folderColor: "#5ccfe6",
			editorSelection: "#33415e",
			// Toast
			toastBackground: "#1f2430",
			toastForeground: "#cbccc6",
			toastBorder: "#343d4a",
		},
	},
	{
		key: "andromeda",
		name: "Andromeda",
		description: "星空紫色主题",
		type: "dark",
		colors: {
			background: "#23262e",
			foreground: "#d5ced9",
			card: "#1b1e26",
			cardForeground: "#d5ced9",
			popover: "#1b1e26",
			popoverForeground: "#d5ced9",
			primary: "#f39c12",
			primaryForeground: "#23262e",
			secondary: "#2b2e36",
			secondaryForeground: "#d5ced9",
			muted: "#2b2e36",
			mutedForeground: "#7e8a98",
			accent: "#2b2e36",
			accentForeground: "#d5ced9",
			border: "#3e4451",
			input: "#3e4451",
			ring: "#f39c12",
			sidebar: "#1b1e26",
			sidebarForeground: "#d5ced9",
			sidebarPrimary: "#f39c12",
			sidebarPrimaryForeground: "#23262e",
			sidebarAccent: "#2b2e36",
			sidebarAccentForeground: "#d5ced9",
			sidebarBorder: "#3e4451",
			folderColor: "#f39c12",
			editorSelection: "#3e4451",
			// Toast
			toastBackground: "#23262e",
			toastForeground: "#d5ced9",
			toastBorder: "#3e4451",
		},
	},
	{
		key: "horizon",
		name: "Horizon",
		description: "地平线主题",
		type: "dark",
		colors: {
			background: "#1c1e26",
			foreground: "#e3e6ee",
			card: "#16161c",
			cardForeground: "#e3e6ee",
			popover: "#16161c",
			popoverForeground: "#e3e6ee",
			primary: "#e95678",
			primaryForeground: "#1c1e26",
			secondary: "#232530",
			secondaryForeground: "#e3e6ee",
			muted: "#232530",
			mutedForeground: "#6c6f93",
			accent: "#2e303e",
			accentForeground: "#e3e6ee",
			border: "#2e303e",
			input: "#2e303e",
			ring: "#e95678",
			sidebar: "#1c1e26",
			sidebarForeground: "#e3e6ee",
			sidebarPrimary: "#e95678",
			sidebarPrimaryForeground: "#1c1e26",
			sidebarAccent: "#2e303e",
			sidebarAccentForeground: "#e3e6ee",
			sidebarBorder: "#2e303e",
			folderColor: "#e95678",
			editorSelection: "#3e4155",
			// Toast
			toastBackground: "#1c1e26",
			toastForeground: "#e3e6ee",
			toastBorder: "#2e303e",
		},
	},
	{
		key: "panda",
		name: "Panda",
		description: "熊猫主题",
		type: "dark",
		colors: {
			background: "#292a2b",
			foreground: "#e6e6e6",
			card: "#1d1e1f",
			cardForeground: "#e6e6e6",
			popover: "#1d1e1f",
			popoverForeground: "#e6e6e6",
			primary: "#19f9d8",
			primaryForeground: "#292a2b",
			secondary: "#373839",
			secondaryForeground: "#e6e6e6",
			muted: "#373839",
			mutedForeground: "#676b79",
			accent: "#373839",
			accentForeground: "#e6e6e6",
			border: "#3f3f40",
			input: "#3f3f40",
			ring: "#19f9d8",
			sidebar: "#292a2b",
			sidebarForeground: "#e6e6e6",
			sidebarPrimary: "#19f9d8",
			sidebarPrimaryForeground: "#292a2b",
			sidebarAccent: "#373839",
			sidebarAccentForeground: "#e6e6e6",
			sidebarBorder: "#3f3f40",
			folderColor: "#19f9d8",
			editorSelection: "#45474a",
			// Toast
			toastBackground: "#292a2b",
			toastForeground: "#e6e6e6",
			toastBorder: "#3f3f40",
		},
	},
	{
		key: "dark-plus",
		name: "Dark+",
		description: "VSCode 默认深色主题",
		type: "dark",
		colors: {
			background: "#1e1e1e",
			foreground: "#d4d4d4",
			card: "#252526",
			cardForeground: "#d4d4d4",
			popover: "#252526",
			popoverForeground: "#d4d4d4",
			primary: "#0e639c",
			primaryForeground: "#ffffff",
			secondary: "#2d2d30",
			secondaryForeground: "#d4d4d4",
			muted: "#2d2d30",
			mutedForeground: "#858585",
			accent: "#094771",
			accentForeground: "#d4d4d4",
			border: "#3e3e42",
			input: "#3e3e42",
			ring: "#0e639c",
			sidebar: "#252526",
			sidebarForeground: "#cccccc",
			sidebarPrimary: "#0e639c",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "#094771",
			sidebarAccentForeground: "#d4d4d4",
			sidebarBorder: "#3e3e42",
			folderColor: "#0e639c",
			editorSelection: "#264f78",
			// Toast
			toastBackground: "#1e1e1e",
			toastForeground: "#d4d4d4",
			toastBorder: "#3e3e42",
		},
	},
	{
		key: "monokai",
		name: "Monokai",
		description: "经典 Monokai 主题",
		type: "dark",
		colors: {
			background: "#272822",
			foreground: "#f8f8f2",
			card: "#1e1f1c",
			cardForeground: "#f8f8f2",
			popover: "#1e1f1c",
			popoverForeground: "#f8f8f2",
			primary: "#66d9ef",
			primaryForeground: "#272822",
			secondary: "#3e3d32",
			secondaryForeground: "#f8f8f2",
			muted: "#3e3d32",
			mutedForeground: "#75715e",
			accent: "#49483e",
			accentForeground: "#f8f8f2",
			border: "#49483e",
			input: "#49483e",
			ring: "#66d9ef",
			sidebar: "#1e1f1c",
			sidebarForeground: "#f8f8f2",
			sidebarPrimary: "#66d9ef",
			sidebarPrimaryForeground: "#272822",
			sidebarAccent: "#49483e",
			sidebarAccentForeground: "#f8f8f2",
			sidebarBorder: "#49483e",
			folderColor: "#66d9ef",
			editorSelection: "#49483e",
			// Toast
			toastBackground: "#272822",
			toastForeground: "#f8f8f2",
			toastBorder: "#49483e",
		},
	},
	{
		key: "tokyo-night-storm",
		name: "Tokyo Night Storm",
		description: "Tokyo Night 暴风版",
		type: "dark",
		colors: {
			background: "#24283b",
			foreground: "#a9b1d6",
			card: "#1f2335",
			cardForeground: "#a9b1d6",
			popover: "#1f2335",
			popoverForeground: "#a9b1d6",
			primary: "#7aa2f7",
			primaryForeground: "#24283b",
			secondary: "#292e42",
			secondaryForeground: "#a9b1d6",
			muted: "#292e42",
			mutedForeground: "#565f89",
			accent: "#3b4261",
			accentForeground: "#a9b1d6",
			border: "#3b4261",
			input: "#3b4261",
			ring: "#7aa2f7",
			sidebar: "#1f2335",
			sidebarForeground: "#a9b1d6",
			sidebarPrimary: "#7aa2f7",
			sidebarPrimaryForeground: "#24283b",
			sidebarAccent: "#3b4261",
			sidebarAccentForeground: "#a9b1d6",
			sidebarBorder: "#3b4261",
			folderColor: "#7aa2f7",
			editorSelection: "#364a82",
			// Toast
			toastBackground: "#24283b",
			toastForeground: "#a9b1d6",
			toastBorder: "#3b4261",
		},
	},
	{
		key: "catppuccin-mocha",
		name: "Catppuccin Mocha",
		description: "温暖的咖啡色主题",
		type: "dark",
		colors: {
			background: "#1e1e2e",
			foreground: "#cdd6f4",
			card: "#181825",
			cardForeground: "#cdd6f4",
			popover: "#181825",
			popoverForeground: "#cdd6f4",
			primary: "#89b4fa",
			primaryForeground: "#1e1e2e",
			secondary: "#313244",
			secondaryForeground: "#cdd6f4",
			muted: "#313244",
			mutedForeground: "#6c7086",
			accent: "#45475a",
			accentForeground: "#cdd6f4",
			border: "#45475a",
			input: "#45475a",
			ring: "#89b4fa",
			sidebar: "#1e1e2e",
			sidebarForeground: "#cdd6f4",
			sidebarPrimary: "#89b4fa",
			sidebarPrimaryForeground: "#1e1e2e",
			sidebarAccent: "#45475a",
			sidebarAccentForeground: "#cdd6f4",
			sidebarBorder: "#45475a",
			folderColor: "#89b4fa",
			editorSelection: "#45475a",
			// Toast
			toastBackground: "#1e1e2e",
			toastForeground: "#cdd6f4",
			toastBorder: "#45475a",
		},
	},
	{
		key: "rose-pine",
		name: "Rosé Pine",
		description: "优雅的玫瑰松木主题",
		type: "dark",
		colors: {
			background: "#191724",
			foreground: "#e0def4",
			card: "#1f1d2e",
			cardForeground: "#e0def4",
			popover: "#1f1d2e",
			popoverForeground: "#e0def4",
			primary: "#c4a7e7",
			primaryForeground: "#191724",
			secondary: "#26233a",
			secondaryForeground: "#e0def4",
			muted: "#26233a",
			mutedForeground: "#6e6a86",
			accent: "#403d52",
			accentForeground: "#e0def4",
			border: "#403d52",
			input: "#403d52",
			ring: "#c4a7e7",
			sidebar: "#191724",
			sidebarForeground: "#e0def4",
			sidebarPrimary: "#c4a7e7",
			sidebarPrimaryForeground: "#191724",
			sidebarAccent: "#403d52",
			sidebarAccentForeground: "#e0def4",
			sidebarBorder: "#403d52",
			folderColor: "#c4a7e7",
			editorSelection: "#403d52",
			// Toast
			toastBackground: "#191724",
			toastForeground: "#e0def4",
			toastBorder: "#403d52",
		},
	},
	{
		key: "github-dark-dimmed",
		name: "GitHub Dark Dimmed",
		description: "GitHub 柔和深色主题",
		type: "dark",
		colors: {
			background: "#22272e",
			foreground: "#adbac7",
			card: "#2d333b",
			cardForeground: "#adbac7",
			popover: "#2d333b",
			popoverForeground: "#adbac7",
			primary: "#539bf5",
			primaryForeground: "#22272e",
			secondary: "#2d333b",
			secondaryForeground: "#adbac7",
			muted: "#2d333b",
			mutedForeground: "#768390",
			accent: "#373e47",
			accentForeground: "#adbac7",
			border: "#444c56",
			input: "#444c56",
			ring: "#539bf5",
			sidebar: "#1c2128",
			sidebarForeground: "#adbac7",
			sidebarPrimary: "#539bf5",
			sidebarPrimaryForeground: "#22272e",
			sidebarAccent: "#373e47",
			sidebarAccentForeground: "#adbac7",
			sidebarBorder: "#444c56",
			folderColor: "#539bf5",
			editorSelection: "#253341",
			// Toast
			toastBackground: "#22272e",
			toastForeground: "#adbac7",
			toastBorder: "#444c56",
		},
	},
	{
		key: "one-monokai",
		name: "One Monokai",
		description: "One Dark 与 Monokai 的完美结合",
		type: "dark",
		colors: {
			background: "#282c34",
			foreground: "#abb2bf",
			card: "#21252b",
			cardForeground: "#abb2bf",
			popover: "#21252b",
			popoverForeground: "#abb2bf",
			primary: "#e06c75",
			primaryForeground: "#282c34",
			secondary: "#3e4451",
			secondaryForeground: "#abb2bf",
			muted: "#3e4451",
			mutedForeground: "#5c6370",
			accent: "#3e4451",
			accentForeground: "#abb2bf",
			border: "#3e4451",
			input: "#3e4451",
			ring: "#e06c75",
			sidebar: "#21252b",
			sidebarForeground: "#abb2bf",
			sidebarPrimary: "#e06c75",
			sidebarPrimaryForeground: "#282c34",
			sidebarAccent: "#3e4451",
			sidebarAccentForeground: "#abb2bf",
			sidebarBorder: "#3e4451",
			folderColor: "#e06c75",
			editorSelection: "#3e4451",
			// Toast
			toastBackground: "#282c34",
			toastForeground: "#abb2bf",
			toastBorder: "#3e4451",
		},
	},
	{
		key: "cyberpunk",
		name: "Cyberpunk",
		description: "赛博朋克高对比度主题",
		type: "dark",
		colors: {
			background: "#020408",
			foreground: "#00ff9c",
			card: "#0b1015",
			cardForeground: "#00ff9c",
			popover: "#0b1015",
			popoverForeground: "#00ff9c",
			primary: "#ff2a6d",
			primaryForeground: "#020408",
			secondary: "#0556f3",
			secondaryForeground: "#ffffff",
			muted: "#0b1015",
			mutedForeground: "#05d9e8",
			accent: "#121820",
			accentForeground: "#00ff9c",
			border: "#05d9e8",
			input: "#05d9e8",
			ring: "#ff2a6d",
			sidebar: "#000000",
			sidebarForeground: "#00ff9c",
			sidebarPrimary: "#ff2a6d",
			sidebarPrimaryForeground: "#020408",
			sidebarAccent: "#121820",
			sidebarAccentForeground: "#00ff9c",
			sidebarBorder: "#0556f3",
			folderColor: "#ff2a6d",
			// Toast - Cyberpunk Neon
			toastBackground: "#0b1015",
			toastForeground: "#00ff9c",
			toastBorder: "#ff2a6d",
			editorSelection: "#21262d",
		},
	},
	{
		key: "noctis",
		name: "Noctis",
		description: "温暖的夜间主题",
		type: "dark",
		colors: {
			background: "#282a36",
			foreground: "#f8f8f2",
			card: "#21222c",
			cardForeground: "#f8f8f2",
			popover: "#21222c",
			popoverForeground: "#f8f8f2",
			primary: "#ff79c6",
			primaryForeground: "#282a36",
			secondary: "#44475a",
			secondaryForeground: "#f8f8f2",
			muted: "#44475a",
			mutedForeground: "#6272a4",
			accent: "#44475a",
			accentForeground: "#f8f8f2",
			border: "#44475a",
			input: "#44475a",
			ring: "#ff79c6",
			sidebar: "#21222c",
			sidebarForeground: "#f8f8f2",
			sidebarPrimary: "#ff79c6",
			sidebarPrimaryForeground: "#282a36",
			sidebarAccent: "#44475a",
			sidebarAccentForeground: "#f8f8f2",
			sidebarBorder: "#44475a",
			folderColor: "#ff79c6",
			editorSelection: "#44475a",
			// Toast
			toastBackground: "#282a36",
			toastForeground: "#f8f8f2",
			toastBorder: "#44475a",
		},
	},
	{
		key: "radical",
		name: "Radical",
		description: "复古未来主义主题",
		type: "dark",
		colors: {
			background: "#141321",
			foreground: "#fe428e",
			card: "#1a1b2f",
			cardForeground: "#fe428e",
			popover: "#1a1b2f",
			popoverForeground: "#fe428e",
			primary: "#f8d847",
			primaryForeground: "#141321",
			secondary: "#2a2139",
			secondaryForeground: "#fe428e",
			muted: "#2a2139",
			mutedForeground: "#484f7d",
			accent: "#282a3a",
			accentForeground: "#fe428e",
			border: "#2a2139",
			input: "#2a2139",
			ring: "#f8d847",
			sidebar: "#141321",
			sidebarForeground: "#fe428e",
			sidebarPrimary: "#f8d847",
			sidebarPrimaryForeground: "#141321",
			sidebarAccent: "#282a3a",
			sidebarAccentForeground: "#fe428e",
			sidebarBorder: "#2a2139",
			folderColor: "#f8d847",
			editorSelection: "#3c1f42",
			// Toast
			toastBackground: "#141321",
			toastForeground: "#fe428e",
			toastBorder: "#2a2139",
		},
	},
];

// 将 camelCase 转换为 kebab-case
function toKebabCase(str: string): string {
	return str.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

// 将十六进制颜色转换为 HSL 格式（用于 Tailwind CSS 变量）
function hexToHSL(hex: string): string {
	// 移除 # 号
	hex = hex.replace(/^#/, "");

	// 处理 3 位十六进制
	if (hex.length === 3) {
		hex = hex
			.split("")
			.map((char) => char + char)
			.join("");
	}

	// 转换为 RGB
	const r = Number.parseInt(hex.substring(0, 2), 16) / 255;
	const g = Number.parseInt(hex.substring(2, 4), 16) / 255;
	const b = Number.parseInt(hex.substring(4, 6), 16) / 255;

	const max = Math.max(r, g, b);
	const min = Math.min(r, g, b);
	let h = 0;
	let s = 0;
	const l = (max + min) / 2;

	if (max !== min) {
		const d = max - min;
		s = l > 0.5 ? d / (2 - max - min) : d / (max + min);

		switch (max) {
			case r:
				h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
				break;
			case g:
				h = ((b - r) / d + 2) / 6;
				break;
			case b:
				h = ((r - g) / d + 4) / 6;
				break;
		}
	}

	// 转换为度数和百分比
	h = Math.round(h * 360);
	s = Math.round(s * 100);
	const lPercent = Math.round(l * 100);

	// 返回 Tailwind CSS 格式：h s% l%
	return `${h} ${s}% ${lPercent}%`;
}

// 生成默认的扩展颜色
function getExtendedColors(
	colors: ThemeColors,
	type: "light" | "dark",
): Required<ThemeColors> {
	return {
		...colors,
		// 编辑器颜色
		editorCursor: colors.editorCursor || colors.primary,
		editorSelection: colors.editorSelection || colors.accent,
		editorLineHighlight:
			colors.editorLineHighlight || (type === "light" ? "#f5f5f5" : "#2a2a2a"),

		// Toast 颜色
		toastBackground: colors.toastBackground || colors.popover,
		toastForeground: colors.toastForeground || colors.popoverForeground,
		toastBorder: colors.toastBorder || colors.border,

		// 状态颜色
		success: colors.success || (type === "light" ? "#22c55e" : "#4ade80"),
		warning: colors.warning || (type === "light" ? "#f59e0b" : "#fbbf24"),
		error: colors.error || (type === "light" ? "#ef4444" : "#f87171"),
		info: colors.info || colors.primary,

		// 语法高亮
		syntaxHeading: colors.syntaxHeading || colors.primary,
		syntaxBold: colors.syntaxBold || (type === "light" ? "#1f2937" : "#f1f5f9"),
		syntaxItalic: colors.syntaxItalic || colors.mutedForeground,
		syntaxLink: colors.syntaxLink || colors.primary,
		syntaxCode: colors.syntaxCode || (type === "light" ? "#dc2626" : "#f87171"),
		syntaxQuote: colors.syntaxQuote || colors.mutedForeground,
		syntaxComment: colors.syntaxComment || colors.mutedForeground,
	};
}

// 应用主题
export function applyTheme(theme: Theme): void {
	const root = document.documentElement;

	// 设置主题类型
	root.classList.remove("light", "dark");
	root.classList.add(theme.type);

	// 获取完整的颜色配置（包括默认扩展颜色）
	const fullColors = getExtendedColors(theme.colors, theme.type);

	// 应用所有颜色变量（直接使用十六进制颜色）
	Object.entries(fullColors).forEach(([key, value]) => {
		root.style.setProperty(`--${toKebabCase(key)}`, value);
	});
}

// 获取主题
export function getThemeByKey(key: string): Theme | undefined {
	return themes.find((t) => t.key === key);
}

// 获取浅色主题
export function getLightThemes(): Theme[] {
	return themes.filter((t) => t.type === "light");
}

// 获取深色主题
export function getDarkThemes(): Theme[] {
	return themes.filter((t) => t.type === "dark");
}
