/**
 * Wiki Builder
 *
 * Implements the Builder pattern for creating Wiki entry objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type { WikiInterface } from "./wiki.interface";
import { WikiSchema } from "./wiki.schema";

/**
 * WikiBuilder class
 *
 * Provides a fluent API for building Wiki entry objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class WikiBuilder {
  private data: Partial<WikiInterface> = {};

  constructor() {
    // Set sensible defaults
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      name: "New Entry",
      alias: [],
      tags: [],
      content: "",
      createDate: now,
      updatedAt: now,
    };
  }

  /**
   * Set the wiki entry ID (optional, auto-generated by default)
   * @param id - UUID for the wiki entry
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set the project/workspace ID
   * @param projectId - UUID of the project this entry belongs to
   * @returns this builder for chaining
   */
  project(projectId: string): this {
    this.data.project = projectId;
    return this;
  }

  /**
   * Set the entry name
   * @param name - Display name for the wiki entry
   * @returns this builder for chaining
   */
  name(name: string): this {
    this.data.name = name;
    return this;
  }

  /**
   * Set the aliases
   * @param alias - Array of alternative names
   * @returns this builder for chaining
   */
  alias(alias: string[]): this {
    this.data.alias = alias;
    return this;
  }

  /**
   * Add a single alias
   * @param aliasName - Alternative name to add
   * @returns this builder for chaining
   */
  addAlias(aliasName: string): this {
    if (!this.data.alias) {
      this.data.alias = [];
    }
    this.data.alias.push(aliasName);
    return this;
  }

  /**
   * Set the tags
   * @param tags - Array of tags for categorization
   * @returns this builder for chaining
   */
  tags(tags: string[]): this {
    this.data.tags = tags;
    return this;
  }

  /**
   * Add a single tag
   * @param tag - Tag to add
   * @returns this builder for chaining
   */
  addTag(tag: string): this {
    if (!this.data.tags) {
      this.data.tags = [];
    }
    this.data.tags.push(tag);
    return this;
  }

  /**
   * Set the content
   * @param content - Rich text content (Lexical JSON)
   * @returns this builder for chaining
   */
  content(content: string): this {
    this.data.content = content;
    return this;
  }

  /**
   * Set the createDate timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  createDate(timestamp: string): this {
    this.data.createDate = timestamp;
    return this;
  }

  /**
   * Set the updatedAt timestamp
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  updatedAt(timestamp: string): this {
    this.data.updatedAt = timestamp;
    return this;
  }

  /**
   * Build and validate the Wiki entry object
   * @returns A validated WikiInterface object
   * @throws ZodError if validation fails
   */
  build(): WikiInterface {
    // Update timestamps if not explicitly set
    const now = dayjs().toISOString();
    if (!this.data.createDate) {
      this.data.createDate = now;
    }
    if (!this.data.updatedAt) {
      this.data.updatedAt = now;
    }

    // Validate and return
    const result = WikiSchema.parse(this.data);
    return result as WikiInterface;
  }

  /**
   * Build a partial Wiki entry object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial WikiInterface object with updated timestamp
   */
  buildPartial(): Partial<WikiInterface> {
    // Always update updatedAt for partial builds
    this.data.updatedAt = dayjs().toISOString();
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      name: "New Entry",
      alias: [],
      tags: [],
      content: "",
      createDate: now,
      updatedAt: now,
    };
    return this;
  }
}
