/**
 * Icon Theme Domain - 配置数据
 * 所有图标主题的定义
 */
import {
	Activity,
	BarChart3,
	Book,
	BookMarked,
	BookOpen,
	BookOpenText,
	BookText,
	Box,
	Calendar,
	CalendarDays,
	CheckSquare,
	Circle,
	ClipboardList,
	Cog,
	Component,
	Database,
	Download,
	Feather,
	File,
	FileBox,
	FileCode,
	FileDown,
	FileEdit,
	FileInput,
	FileOutput,
	FileSearch,
	Files,
	FileTerminal,
	FileText,
	FileUp,
	Flower2,
	Folder,
	FolderClosed,
	FolderOpen,
	FolderOutput,
	FolderTree,
	Gauge,
	GitFork,
	Globe,
	Grid,
	Grid3x3,
	HardDrive,
	Hash,
	Heart,
	HelpCircle,
	Image as ImageIcon,
	Info,
	Layers,
	LayoutTemplate,
	Library,
	LifeBuoy,
	List,
	ListChecks,
	ListTodo,
	ListTree,
	Map as MapIcon,
	Menu,
	Monitor,
	Moon,
	MoreHorizontal,
	MoreVertical,
	Mountain,
	Move,
	Network,
	Notebook,
	NotepadText,
	Package,
	Palette,
	Pencil,
	PenTool,
	PieChart,
	Plus,
	PlusCircle,
	Receipt,
	Ruler,
	Scroll,
	ScrollText,
	Search,
	Server,
	Settings,
	Settings2,
	Share,
	Share2,
	Sliders,
	Smile,
	Sparkles,
	Square,
	Star,
	StickyNote,
	Sun,
	Tag,
	Tags,
	Terminal,
	TrendingUp,
	Type,
	Upload,
	User,
	UserCog,
	Users,
	Wallet,
	Wand2,
	Waves,
	Workflow,
	Wrench,
} from "lucide-react"
import type { IconTheme } from "./icon-theme.interface"

export const iconThemes: readonly IconTheme[] = [
	{
		author: "Novel Editor Team",
		description: "Novel Editor default icon theme",
		icons: {
			activityBar: {
				canvas: Pencil,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: CalendarDays,
				export: Download,
				files: Files,
				import: Upload,
				ledger: Wallet,
				library: BookMarked,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: StickyNote,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: TrendingUp,
				tags: Tags,
				todo: ListTodo,
			},
			character: { default: User },
			file: { default: FileText },
			folder: { default: Folder, open: FolderOpen },
			project: { default: Book, open: BookOpen },
			settingsPage: {
				about: Info,
				appearance: Palette,
				data: Database,
				diagrams: BarChart3,
				editor: Type,
				export: FolderOutput,
				general: Settings2,
				icons: Sparkles,
				logs: ScrollText,
				scroll: Activity,
			},
			world: { default: Globe },
		},
		key: "default",
		name: "Default",
	},
	{
		author: "Novel Editor Team",
		description: "Clean and unified icon style",
		icons: {
			activityBar: {
				canvas: Pencil,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Download,
				files: Files,
				import: Upload,
				ledger: Wallet,
				library: Book,
				mermaid: Workflow,
				more: Menu,
				note: FileText,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Cog,
				statistics: BarChart3,
				tags: Tag,
				todo: CheckSquare,
			},
			character: { default: File },
			file: { default: File },
			folder: { default: Folder },
			project: { default: Book },
			settingsPage: {
				about: HelpCircle,
				appearance: Circle,
				data: Database,
				diagrams: Square,
				editor: Type,
				export: Download,
				general: Sliders,
				icons: Star,
				logs: List,
				scroll: Move,
			},
			world: { default: File },
		},
		key: "minimal",
		name: "Minimal",
	},
	{
		author: "Novel Editor Team",
		description: "Traditional file icon style",
		icons: {
			activityBar: {
				canvas: Pencil,
				chapters: FolderTree,
				code: FileCode,
				create: PlusCircle,
				diary: CalendarDays,
				export: FileDown,
				files: Files,
				import: FileUp,
				ledger: Wallet,
				library: BookMarked,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: NotepadText,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: TrendingUp,
				tags: Tags,
				todo: ListChecks,
			},
			character: { default: User },
			file: { default: FileText },
			folder: { default: Folder, open: FolderOpen },
			project: { default: BookMarked, open: BookOpen },
			settingsPage: {
				about: Info,
				appearance: Palette,
				data: HardDrive,
				diagrams: PieChart,
				editor: FileEdit,
				export: FileOutput,
				general: Settings,
				icons: Sparkles,
				logs: FileText,
				scroll: Scroll,
			},
			world: { default: BookMarked },
		},
		key: "classic",
		name: "Classic",
	},
	{
		author: "Novel Editor Team",
		description: "Modern icon design",
		icons: {
			activityBar: {
				canvas: Palette,
				chapters: FolderTree,
				code: FileCode,
				create: PlusCircle,
				diary: CalendarDays,
				export: FileDown,
				files: Files,
				import: FileUp,
				ledger: Wallet,
				library: Library,
				mermaid: Workflow,
				more: Menu,
				note: StickyNote,
				outline: Grid3x3,
				plantuml: GitFork,
				search: Search,
				settings: Cog,
				statistics: BarChart3,
				tags: Tags,
				todo: ListTodo,
			},
			character: { default: Users },
			file: { default: FileEdit },
			folder: { default: FolderTree, open: FolderOpen },
			project: { default: Library, open: BookOpenText },
			settingsPage: {
				about: LifeBuoy,
				appearance: LayoutTemplate,
				data: Server,
				diagrams: BarChart3,
				editor: PenTool,
				export: Share,
				general: Sliders,
				icons: Grid,
				logs: FileCode,
				scroll: Waves,
			},
			world: { default: MapIcon },
		},
		key: "modern",
		name: "Modern",
	},
	{
		author: "Novel Editor Team",
		description: "Elegant and exquisite icon style",
		icons: {
			activityBar: {
				canvas: Feather,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: CalendarDays,
				export: Download,
				files: Files,
				import: Upload,
				ledger: Wallet,
				library: BookText,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: ScrollText,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: TrendingUp,
				tags: Tags,
				todo: ListChecks,
			},
			character: { default: User },
			file: { default: ScrollText },
			folder: { default: Layers, open: FolderOpen },
			project: { default: BookText, open: BookOpen },
			settingsPage: {
				about: HelpCircle,
				appearance: Wand2,
				data: Database,
				diagrams: Activity,
				editor: Feather,
				export: FolderOutput,
				general: Settings2,
				icons: Star,
				logs: ScrollText,
				scroll: Scroll,
			},
			world: { default: Sparkles },
		},
		key: "elegant",
		name: "Elegant",
	},
	{
		author: "Novel Editor Team",
		description: "Icon theme designed for writing",
		icons: {
			activityBar: {
				canvas: Feather,
				chapters: FolderTree,
				code: FileCode,
				create: PenTool,
				diary: CalendarDays,
				export: Download,
				files: Files,
				import: Upload,
				ledger: Wallet,
				library: Notebook,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: NotepadText,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: TrendingUp,
				tags: Tags,
				todo: ListTodo,
			},
			character: { default: Users },
			file: { default: Feather },
			folder: { default: Folder, open: FolderOpen },
			project: { default: Notebook, open: BookOpen },
			settingsPage: {
				about: Info,
				appearance: Palette,
				data: Book,
				diagrams: TrendingUp,
				editor: Pencil,
				export: FileOutput,
				general: Settings,
				icons: Sparkles,
				logs: FileText,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "writer",
		name: "Writer",
	},
	{
		author: "Novel Editor Team",
		description: "Hard-edged technical style icons",
		icons: {
			activityBar: {
				canvas: Ruler,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Terminal,
				export: FileOutput,
				files: FileBox,
				import: FileInput,
				ledger: Receipt,
				library: Database,
				mermaid: Workflow,
				more: MoreVertical,
				note: FileCode,
				outline: Share2,
				plantuml: GitFork,
				search: FileSearch,
				settings: Wrench,
				statistics: Gauge,
				tags: Hash,
				todo: ClipboardList,
			},
			character: { default: UserCog },
			file: { default: FileCode },
			folder: { default: FolderClosed, open: FolderOpen },
			project: { default: Box, open: Package },
			settingsPage: {
				about: Info,
				appearance: Monitor,
				data: Server,
				diagrams: Gauge,
				editor: Terminal,
				export: HardDrive,
				general: Cog,
				icons: Component,
				logs: FileTerminal,
				scroll: Activity,
			},
			world: { default: Network },
		},
		key: "technical",
		name: "Technical",
	},
	{
		author: "Novel Editor Team",
		description: "Fresh and natural icon style",
		icons: {
			activityBar: {
				canvas: Palette,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Sun,
				export: Download,
				files: Files,
				import: Upload,
				ledger: Wallet,
				library: Flower2,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: Feather,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: TrendingUp,
				tags: Tags,
				todo: ListChecks,
			},
			character: { default: Smile },
			file: { default: File },
			folder: { default: Folder, open: FolderOpen },
			project: { default: Flower2, open: Flower2 },
			settingsPage: {
				about: Heart,
				appearance: Sun,
				data: Database,
				diagrams: TrendingUp,
				editor: Feather,
				export: FolderOutput,
				general: Settings2,
				icons: Flower2,
				logs: ScrollText,
				scroll: Waves,
			},
			world: { default: Mountain },
		},
		key: "nature",
		name: "Nature",
	},
	{
		author: "Novel Editor Team",
		description: "Developer focused icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Receipt,
				library: Terminal,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: FileText,
				outline: ListTree,
				plantuml: GitFork,
				search: FileSearch,
				settings: Cog,
				statistics: Activity,
				tags: Hash,
				todo: CheckSquare,
			},
			character: { default: UserCog },
			file: { default: FileCode },
			folder: { default: FolderClosed, open: FolderOpen },
			project: { default: Terminal, open: Terminal },
			settingsPage: {
				about: Info,
				appearance: Monitor,
				data: Database,
				diagrams: Activity,
				editor: Terminal,
				export: HardDrive,
				general: Cog,
				icons: Component,
				logs: FileTerminal,
				scroll: Move,
			},
			world: { default: Globe },
		},
		key: "code",
		name: "Code Icons",
	},
	{
		author: "Novel Editor Team",
		description: "Professional office icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: PlusCircle,
				diary: CalendarDays,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Wallet,
				library: Scroll,
				mermaid: Workflow,
				more: MoreVertical,
				note: FileText,
				outline: List,
				plantuml: GitFork,
				search: Search,
				settings: Settings2,
				statistics: BarChart3,
				tags: Tag,
				todo: ListChecks,
			},
			character: { default: User },
			file: { default: FileText },
			folder: { default: Folder, open: FolderOpen },
			project: { default: Scroll, open: ScrollText },
			settingsPage: {
				about: Info,
				appearance: LayoutTemplate,
				data: Database,
				diagrams: BarChart3,
				editor: FileEdit,
				export: Share,
				general: Settings2,
				icons: Grid,
				logs: List,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "business",
		name: "Business Icons",
	},
	{
		author: "Novel Editor Team",
		description: "Artistic and expressive icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Sun,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Wallet,
				library: Palette,
				mermaid: Workflow,
				more: Menu,
				note: StickyNote,
				outline: Grid3x3,
				plantuml: GitFork,
				search: Search,
				settings: Sliders,
				statistics: PieChart,
				tags: Star,
				todo: ListTodo,
			},
			character: { default: Smile },
			file: { default: ImageIcon },
			folder: { default: Layers, open: Layers },
			project: { default: Palette, open: Palette },
			settingsPage: {
				about: Heart,
				appearance: Palette,
				data: HardDrive,
				diagrams: PieChart,
				editor: PenTool,
				export: Share2,
				general: Sliders,
				icons: Sparkles,
				logs: ScrollText,
				scroll: Waves,
			},
			world: { default: Sparkles },
		},
		key: "creative",
		name: "Creative Icons",
	},
	{
		author: "Novel Editor Team",
		description: "Scholarly and research icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Wallet,
				library: Library,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: NotepadText,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: BarChart3,
				tags: Tags,
				todo: CheckSquare,
			},
			character: { default: User },
			file: { default: FileText },
			folder: { default: Library, open: Library },
			project: { default: Book, open: BookOpen },
			settingsPage: {
				about: HelpCircle,
				appearance: Book,
				data: Database,
				diagrams: BarChart3,
				editor: FileEdit,
				export: FileUp,
				general: Settings,
				icons: Grid,
				logs: FileText,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "academic",
		name: "Academic Icons",
	},
	{
		author: "Novel Editor Team",
		description: "Computer hardware icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Receipt,
				library: HardDrive,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: FileText,
				outline: Grid,
				plantuml: GitFork,
				search: Search,
				settings: Cog,
				statistics: Activity,
				tags: Hash,
				todo: ClipboardList,
			},
			character: { default: User },
			file: { default: HardDrive },
			folder: { default: Server, open: Server },
			project: { default: Monitor, open: Monitor },
			settingsPage: {
				about: Info,
				appearance: Monitor,
				data: Database,
				diagrams: Activity,
				editor: Terminal,
				export: HardDrive,
				general: Cog,
				icons: Component,
				logs: FileTerminal,
				scroll: Move,
			},
			world: { default: Network },
		},
		key: "hardware",
		name: "Hardware",
	},
	{
		author: "Novel Editor Team",
		description: "Utility and tools icons",
		icons: {
			activityBar: {
				canvas: Ruler,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Receipt,
				library: Wrench,
				mermaid: Workflow,
				more: MoreVertical,
				note: FileText,
				outline: List,
				plantuml: GitFork,
				search: Search,
				settings: Settings2,
				statistics: Gauge,
				tags: Tag,
				todo: CheckSquare,
			},
			character: { default: UserCog },
			file: { default: File },
			folder: { default: Package, open: Package },
			project: { default: Wrench, open: Wrench },
			settingsPage: {
				about: Info,
				appearance: LayoutTemplate,
				data: Database,
				diagrams: Gauge,
				editor: FileEdit,
				export: Share,
				general: Settings2,
				icons: Grid,
				logs: List,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "tools",
		name: "Tools",
	},
	{
		author: "Novel Editor Team",
		description: "Geometric shape icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Wallet,
				library: Box,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: Square,
				outline: Grid,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: PieChart,
				tags: Tag,
				todo: CheckSquare,
			},
			character: { default: User },
			file: { default: Circle },
			folder: { default: Square, open: Square },
			project: { default: Box, open: Box },
			settingsPage: {
				about: Info,
				appearance: Palette,
				data: Database,
				diagrams: PieChart,
				editor: FileEdit,
				export: FileUp,
				general: Settings,
				icons: Grid,
				logs: FileText,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "shapes",
		name: "Shapes",
	},
	{
		author: "Novel Editor Team",
		description: "Heart and affection icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Wallet,
				library: Heart,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: StickyNote,
				outline: List,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: TrendingUp,
				tags: Tag,
				todo: ListChecks,
			},
			character: { default: Smile },
			file: { default: FileText },
			folder: { default: Folder, open: FolderOpen },
			project: { default: Heart, open: Heart },
			settingsPage: {
				about: Info,
				appearance: Heart,
				data: Database,
				diagrams: TrendingUp,
				editor: FileEdit,
				export: FileUp,
				general: Settings,
				icons: Sparkles,
				logs: FileText,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "love",
		name: "Love",
	},
	{
		author: "Novel Editor Team",
		description: "Dark mode optimized icons",
		icons: {
			activityBar: {
				canvas: PenTool,
				chapters: FolderTree,
				code: FileCode,
				create: Plus,
				diary: Calendar,
				export: Upload,
				files: Files,
				import: Download,
				ledger: Wallet,
				library: Moon,
				mermaid: Workflow,
				more: MoreHorizontal,
				note: FileText,
				outline: ListTree,
				plantuml: GitFork,
				search: Search,
				settings: Settings,
				statistics: BarChart3,
				tags: Star,
				todo: CheckSquare,
			},
			character: { default: User },
			file: { default: File },
			folder: { default: Folder, open: FolderOpen },
			project: { default: Moon, open: Moon },
			settingsPage: {
				about: Info,
				appearance: Moon,
				data: Database,
				diagrams: BarChart3,
				editor: FileEdit,
				export: FileUp,
				general: Settings,
				icons: Star,
				logs: FileText,
				scroll: Scroll,
			},
			world: { default: Globe },
		},
		key: "night",
		name: "Night",
	},
]
