/**
 * Content Builder
 *
 * Implements the Builder pattern for creating Content objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2, 3.4, 3.5
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type { ContentInterface, ContentType } from "./content.interface";
import { ContentSchema } from "./content.schema";

/**
 * ContentBuilder class
 *
 * Provides a fluent API for building Content objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class ContentBuilder {
  private data: Partial<ContentInterface> = {};

  constructor() {
    // Set sensible defaults
    this.data = {
      id: uuidv4(),
      content: "",
      contentType: "lexical",
      lastEdit: dayjs().toISOString(),
    };
  }

  /**
   * Set the node ID this content belongs to
   * @param id - UUID of the parent node
   * @returns this builder for chaining
   */
  nodeId(id: string): this {
    this.data.nodeId = id;
    return this;
  }

  /**
   * Set the content string
   * @param content - The content (Lexical JSON, Excalidraw JSON, or plain text)
   * @returns this builder for chaining
   */
  content(content: string): this {
    this.data.content = content;
    return this;
  }

  /**
   * Set the content type
   * @param type - The type of content ("lexical" | "excalidraw" | "text")
   * @returns this builder for chaining
   */
  contentType(type: ContentType): this {
    this.data.contentType = type;
    return this;
  }

  /**
   * Set a custom ID (optional, auto-generated by default)
   * @param id - UUID for the content record
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set a custom lastEdit timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  lastEdit(timestamp: string): this {
    this.data.lastEdit = timestamp;
    return this;
  }

  /**
   * Build and validate the Content object
   * @returns A validated ContentInterface object
   * @throws ZodError if validation fails
   */
  build(): ContentInterface {
    // Update lastEdit to current time if not explicitly set
    if (!this.data.lastEdit) {
      this.data.lastEdit = dayjs().toISOString();
    }

    // Validate and return
    const result = ContentSchema.parse(this.data);
    return result as ContentInterface;
  }

  /**
   * Build a partial Content object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial ContentInterface object with updated lastEdit
   */
  buildPartial(): Partial<ContentInterface> {
    // Always update lastEdit for partial builds
    this.data.lastEdit = dayjs().toISOString();
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    this.data = {
      id: uuidv4(),
      content: "",
      contentType: "lexical",
      lastEdit: dayjs().toISOString(),
    };
    return this;
  }
}
