/**
 * Icon Theme Domain - 配置数据
 * 所有图标主题的定义
 */
import {
	Activity,
	BarChart3,
	Book,
	BookMarked,
	BookOpen,
	BookOpenText,
	BookText,
	Box,
	Calendar,
	CalendarDays,
	Circle,
	Cog,
	Component,
	Database,
	Download,
	Feather,
	File,
	FileBox,
	FileCode,
	FileDown,
	FileEdit,
	FileInput,
	FileOutput,
	FileSearch,
	FileTerminal,
	FileText,
	FileUp,
	Files,
	Flower2,
	Folder,
	FolderClosed,
	FolderOpen,
	FolderOutput,
	FolderTree,
	Gauge,
	Globe,
	Grid,
	Grid3x3,
	HardDrive,
	Hash,
	Heart,
	HelpCircle,
	Image as ImageIcon,
	Info,
	Layers,
	LayoutTemplate,
	Library,
	LifeBuoy,
	List,
	ListTree,
	Map as MapIcon,
	Menu,
	Monitor,
	Moon,
	MoreHorizontal,
	MoreVertical,
	Mountain,
	Move,
	Network,
	Notebook,
	Package,
	Palette,
	PenTool,
	Pencil,
	PieChart,
	Plus,
	PlusCircle,
	Ruler,
	Scroll,
	ScrollText,
	Search,
	Server,
	Settings,
	Settings2,
	Share,
	Share2,
	Sliders,
	Smile,
	Sparkles,
	Square,
	Star,
	Sun,
	Tag,
	Tags,
	Terminal,
	TrendingUp,
	Type,
	Upload,
	User,
	UserCog,
	Users,
	Wand2,
	Waves,
	Wrench,
} from "lucide-react";
import type { IconTheme } from "./icon-theme.interface";

export const iconThemes: IconTheme[] = [
	{
		key: "default",
		name: "Default",
		description: "Novel Editor default icon theme",
		author: "Novel Editor Team",
		icons: {
			project: { default: Book, open: BookOpen },
			folder: { default: Folder, open: FolderOpen },
			file: { default: FileText },
			character: { default: User },
			world: { default: Globe },
			activityBar: {
				library: BookMarked, search: Search, outline: ListTree, canvas: Pencil,
				chapters: FolderTree, files: Files, diary: CalendarDays, tags: Tags,
				statistics: TrendingUp, settings: Settings, create: Plus,
				import: Upload, export: Download, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Palette, icons: Sparkles, diagrams: BarChart3,
				general: Settings2, editor: Type, data: Database,
				export: FolderOutput, scroll: Activity, logs: ScrollText, about: Info,
			},
		},
	},
	{
		key: "minimal",
		name: "Minimal",
		description: "Clean and unified icon style",
		author: "Novel Editor Team",
		icons: {
			project: { default: Book },
			folder: { default: Folder },
			file: { default: File },
			character: { default: File },
			world: { default: File },
			activityBar: {
				library: Book, search: Search, outline: ListTree, canvas: Pencil,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Tag,
				statistics: BarChart3, settings: Cog, create: Plus,
				import: Upload, export: Download, more: Menu,
			},
			settingsPage: {
				appearance: Circle, icons: Star, diagrams: Square,
				general: Sliders, editor: Type, data: Database,
				export: Download, scroll: Move, logs: List, about: HelpCircle,
			},
		},
	},
	{
		key: "classic",
		name: "Classic",
		description: "Traditional file icon style",
		author: "Novel Editor Team",
		icons: {
			project: { default: BookMarked, open: BookOpen },
			folder: { default: Folder, open: FolderOpen },
			file: { default: FileText },
			character: { default: User },
			world: { default: BookMarked },
			activityBar: {
				library: BookMarked, search: Search, outline: ListTree, canvas: Pencil,
				chapters: FolderTree, files: Files, diary: CalendarDays, tags: Tags,
				statistics: TrendingUp, settings: Settings, create: PlusCircle,
				import: FileUp, export: FileDown, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Palette, icons: Sparkles, diagrams: PieChart,
				general: Settings, editor: FileEdit, data: HardDrive,
				export: FileOutput, scroll: Scroll, logs: FileText, about: Info,
			},
		},
	},
	{
		key: "modern",
		name: "Modern",
		description: "Modern icon design",
		author: "Novel Editor Team",
		icons: {
			project: { default: Library, open: BookOpenText },
			folder: { default: FolderTree, open: FolderOpen },
			file: { default: FileEdit },
			character: { default: Users },
			world: { default: MapIcon },
			activityBar: {
				library: Library, search: Search, outline: Grid3x3, canvas: Palette,
				chapters: FolderTree, files: Files, diary: CalendarDays, tags: Tags,
				statistics: BarChart3, settings: Cog, create: PlusCircle,
				import: FileUp, export: FileDown, more: Menu,
			},
			settingsPage: {
				appearance: LayoutTemplate, icons: Grid, diagrams: BarChart3,
				general: Sliders, editor: PenTool, data: Server,
				export: Share, scroll: Waves, logs: FileCode, about: LifeBuoy,
			},
		},
	},
	{
		key: "elegant",
		name: "Elegant",
		description: "Elegant and exquisite icon style",
		author: "Novel Editor Team",
		icons: {
			project: { default: BookText, open: BookOpen },
			folder: { default: Layers, open: FolderOpen },
			file: { default: ScrollText },
			character: { default: User },
			world: { default: Sparkles },
			activityBar: {
				library: BookText, search: Search, outline: ListTree, canvas: Feather,
				chapters: FolderTree, files: Files, diary: CalendarDays, tags: Tags,
				statistics: TrendingUp, settings: Settings, create: Plus,
				import: Upload, export: Download, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Wand2, icons: Star, diagrams: Activity,
				general: Settings2, editor: Feather, data: Database,
				export: FolderOutput, scroll: Scroll, logs: ScrollText, about: HelpCircle,
			},
		},
	},
	{
		key: "writer",
		name: "Writer",
		description: "Icon theme designed for writing",
		author: "Novel Editor Team",
		icons: {
			project: { default: Notebook, open: BookOpen },
			folder: { default: Folder, open: FolderOpen },
			file: { default: Feather },
			character: { default: Users },
			world: { default: Globe },
			activityBar: {
				library: Notebook, search: Search, outline: ListTree, canvas: Feather,
				chapters: FolderTree, files: Files, diary: CalendarDays, tags: Tags,
				statistics: TrendingUp, settings: Settings, create: PenTool,
				import: Upload, export: Download, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Palette, icons: Sparkles, diagrams: TrendingUp,
				general: Settings, editor: Pencil, data: Book,
				export: FileOutput, scroll: Scroll, logs: FileText, about: Info,
			},
		},
	},
	{
		key: "technical",
		name: "Technical",
		description: "Hard-edged technical style icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Box, open: Package },
			folder: { default: FolderClosed, open: FolderOpen },
			file: { default: FileCode },
			character: { default: UserCog },
			world: { default: Network },
			activityBar: {
				library: Database, search: FileSearch, outline: Share2, canvas: Ruler,
				chapters: FolderTree, files: FileBox, diary: Terminal, tags: Hash,
				statistics: Gauge, settings: Wrench, create: Plus,
				import: FileInput, export: FileOutput, more: MoreVertical,
			},
			settingsPage: {
				appearance: Monitor, icons: Component, diagrams: Gauge,
				general: Cog, editor: Terminal, data: Server,
				export: HardDrive, scroll: Activity, logs: FileTerminal, about: Info,
			},
		},
	},
	{
		key: "nature",
		name: "Nature",
		description: "Fresh and natural icon style",
		author: "Novel Editor Team",
		icons: {
			project: { default: Flower2, open: Flower2 },
			folder: { default: Folder, open: FolderOpen },
			file: { default: File },
			character: { default: Smile },
			world: { default: Mountain },
			activityBar: {
				library: Flower2, search: Search, outline: ListTree, canvas: Palette,
				chapters: FolderTree, files: Files, diary: Sun, tags: Tags,
				statistics: TrendingUp, settings: Settings, create: Plus,
				import: Upload, export: Download, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Sun, icons: Flower2, diagrams: TrendingUp,
				general: Settings2, editor: Feather, data: Database,
				export: FolderOutput, scroll: Waves, logs: ScrollText, about: Heart,
			},
		},
	},
	{
		key: "code",
		name: "Code Icons",
		description: "Developer focused icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Terminal, open: Terminal },
			folder: { default: FolderClosed, open: FolderOpen },
			file: { default: FileCode },
			character: { default: UserCog },
			world: { default: Globe },
			activityBar: {
				library: Terminal, search: FileSearch, outline: ListTree, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Hash,
				statistics: Activity, settings: Cog, create: Plus,
				import: Download, export: Upload, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Monitor, icons: Component, diagrams: Activity,
				general: Cog, editor: Terminal, data: Database,
				export: HardDrive, scroll: Move, logs: FileTerminal, about: Info,
			},
		},
	},
	{
		key: "business",
		name: "Business Icons",
		description: "Professional office icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Scroll, open: ScrollText },
			folder: { default: Folder, open: FolderOpen },
			file: { default: FileText },
			character: { default: User },
			world: { default: Globe },
			activityBar: {
				library: Scroll, search: Search, outline: List, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: CalendarDays, tags: Tag,
				statistics: BarChart3, settings: Settings2, create: PlusCircle,
				import: Download, export: Upload, more: MoreVertical,
			},
			settingsPage: {
				appearance: LayoutTemplate, icons: Grid, diagrams: BarChart3,
				general: Settings2, editor: FileEdit, data: Database,
				export: Share, scroll: Scroll, logs: List, about: Info,
			},
		},
	},
	{
		key: "creative",
		name: "Creative Icons",
		description: "Artistic and expressive icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Palette, open: Palette },
			folder: { default: Layers, open: Layers },
			file: { default: ImageIcon },
			character: { default: Smile },
			world: { default: Sparkles },
			activityBar: {
				library: Palette, search: Search, outline: Grid3x3, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Sun, tags: Star,
				statistics: PieChart, settings: Sliders, create: Plus,
				import: Download, export: Upload, more: Menu,
			},
			settingsPage: {
				appearance: Palette, icons: Sparkles, diagrams: PieChart,
				general: Sliders, editor: PenTool, data: HardDrive,
				export: Share2, scroll: Waves, logs: ScrollText, about: Heart,
			},
		},
	},
	{
		key: "academic",
		name: "Academic Icons",
		description: "Scholarly and research icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Book, open: BookOpen },
			folder: { default: Library, open: Library },
			file: { default: FileText },
			character: { default: User },
			world: { default: Globe },
			activityBar: {
				library: Library, search: Search, outline: ListTree, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Tags,
				statistics: BarChart3, settings: Settings, create: Plus,
				import: Download, export: Upload, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Book, icons: Grid, diagrams: BarChart3,
				general: Settings, editor: FileEdit, data: Database,
				export: FileUp, scroll: Scroll, logs: FileText, about: HelpCircle,
			},
		},
	},
	{
		key: "hardware",
		name: "Hardware",
		description: "Computer hardware icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Monitor, open: Monitor },
			folder: { default: Server, open: Server },
			file: { default: HardDrive },
			character: { default: User },
			world: { default: Network },
			activityBar: {
				library: HardDrive, search: Search, outline: Grid, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Hash,
				statistics: Activity, settings: Cog, create: Plus,
				import: Download, export: Upload, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Monitor, icons: Component, diagrams: Activity,
				general: Cog, editor: Terminal, data: Database,
				export: HardDrive, scroll: Move, logs: FileTerminal, about: Info,
			},
		},
	},
	{
		key: "tools",
		name: "Tools",
		description: "Utility and tools icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Wrench, open: Wrench },
			folder: { default: Package, open: Package },
			file: { default: File },
			character: { default: UserCog },
			world: { default: Globe },
			activityBar: {
				library: Wrench, search: Search, outline: List, canvas: Ruler,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Tag,
				statistics: Gauge, settings: Settings2, create: Plus,
				import: Download, export: Upload, more: MoreVertical,
			},
			settingsPage: {
				appearance: LayoutTemplate, icons: Grid, diagrams: Gauge,
				general: Settings2, editor: FileEdit, data: Database,
				export: Share, scroll: Scroll, logs: List, about: Info,
			},
		},
	},
	{
		key: "shapes",
		name: "Shapes",
		description: "Geometric shape icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Box, open: Box },
			folder: { default: Square, open: Square },
			file: { default: Circle },
			character: { default: User },
			world: { default: Globe },
			activityBar: {
				library: Box, search: Search, outline: Grid, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Tag,
				statistics: PieChart, settings: Settings, create: Plus,
				import: Download, export: Upload, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Palette, icons: Grid, diagrams: PieChart,
				general: Settings, editor: FileEdit, data: Database,
				export: FileUp, scroll: Scroll, logs: FileText, about: Info,
			},
		},
	},
	{
		key: "love",
		name: "Love",
		description: "Heart and affection icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Heart, open: Heart },
			folder: { default: Folder, open: FolderOpen },
			file: { default: FileText },
			character: { default: Smile },
			world: { default: Globe },
			activityBar: {
				library: Heart, search: Search, outline: List, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Tag,
				statistics: TrendingUp, settings: Settings, create: Plus,
				import: Download, export: Upload, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Heart, icons: Sparkles, diagrams: TrendingUp,
				general: Settings, editor: FileEdit, data: Database,
				export: FileUp, scroll: Scroll, logs: FileText, about: Info,
			},
		},
	},
	{
		key: "night",
		name: "Night",
		description: "Dark mode optimized icons",
		author: "Novel Editor Team",
		icons: {
			project: { default: Moon, open: Moon },
			folder: { default: Folder, open: FolderOpen },
			file: { default: File },
			character: { default: User },
			world: { default: Globe },
			activityBar: {
				library: Moon, search: Search, outline: ListTree, canvas: PenTool,
				chapters: FolderTree, files: Files, diary: Calendar, tags: Star,
				statistics: BarChart3, settings: Settings, create: Plus,
				import: Download, export: Upload, more: MoreHorizontal,
			},
			settingsPage: {
				appearance: Moon, icons: Star, diagrams: BarChart3,
				general: Settings, editor: FileEdit, data: Database,
				export: FileUp, scroll: Scroll, logs: FileText, about: Info,
			},
		},
	},
];
