/**
 * Workspace Builder
 *
 * Implements the Builder pattern for creating Workspace objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type { WorkspaceInterface } from "./workspace.interface";
import { WorkspaceSchema } from "./workspace.schema";

/**
 * WorkspaceBuilder class
 *
 * Provides a fluent API for building Workspace objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class WorkspaceBuilder {
  private data: Partial<WorkspaceInterface> = {};

  constructor() {
    // Set sensible defaults
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      title: "New Workspace",
      author: "",
      description: "",
      publisher: "",
      language: "zh",
      lastOpen: now,
      createDate: now,
    };
  }

  /**
   * Set the workspace ID (optional, auto-generated by default)
   * @param id - UUID for the workspace
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set the workspace title
   * @param title - Display title for the workspace
   * @returns this builder for chaining
   */
  title(title: string): this {
    this.data.title = title;
    return this;
  }

  /**
   * Set the author name
   * @param author - Author name
   * @returns this builder for chaining
   */
  author(author: string): this {
    this.data.author = author;
    return this;
  }

  /**
   * Set the description
   * @param description - Project description
   * @returns this builder for chaining
   */
  description(description: string): this {
    this.data.description = description;
    return this;
  }

  /**
   * Set the publisher
   * @param publisher - Publisher information
   * @returns this builder for chaining
   */
  publisher(publisher: string): this {
    this.data.publisher = publisher;
    return this;
  }

  /**
   * Set the language
   * @param language - Project language (e.g., "zh", "en")
   * @returns this builder for chaining
   */
  language(language: string): this {
    this.data.language = language;
    return this;
  }

  /**
   * Set the lastOpen timestamp
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  lastOpen(timestamp: string): this {
    this.data.lastOpen = timestamp;
    return this;
  }

  /**
   * Set the createDate timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  createDate(timestamp: string): this {
    this.data.createDate = timestamp;
    return this;
  }

  /**
   * Set the team members
   * @param members - Array of user IDs
   * @returns this builder for chaining
   */
  members(members: string[]): this {
    this.data.members = members;
    return this;
  }

  /**
   * Set the owner
   * @param ownerId - Owner user ID
   * @returns this builder for chaining
   */
  owner(ownerId: string): this {
    this.data.owner = ownerId;
    return this;
  }

  /**
   * Build and validate the Workspace object
   * @returns A validated WorkspaceInterface object
   * @throws ZodError if validation fails
   */
  build(): WorkspaceInterface {
    // Update lastOpen to current time if not explicitly set after construction
    const now = dayjs().toISOString();
    if (!this.data.lastOpen) {
      this.data.lastOpen = now;
    }
    if (!this.data.createDate) {
      this.data.createDate = now;
    }

    // Validate and return
    const result = WorkspaceSchema.parse(this.data);
    return result as WorkspaceInterface;
  }

  /**
   * Build a partial Workspace object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial WorkspaceInterface object with updated lastOpen
   */
  buildPartial(): Partial<WorkspaceInterface> {
    // Always update lastOpen for partial builds
    this.data.lastOpen = dayjs().toISOString();
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      title: "New Workspace",
      author: "",
      description: "",
      publisher: "",
      language: "zh",
      lastOpen: now,
      createDate: now,
    };
    return this;
  }
}
