/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogRouteImport } from './routes/log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsDesignRouteImport } from './routes/settings/design'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'

const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDesignRoute = SettingsDesignRouteImport.update({
  id: '/settings/design',
  path: '/settings/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/design': typeof SettingsDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/design': typeof SettingsDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/design': typeof SettingsDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/log' | '/projects/$projectId' | '/settings/design'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/log' | '/projects/$projectId' | '/settings/design'
  id: '__root__' | '/' | '/log' | '/projects/$projectId' | '/settings/design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SettingsDesignRoute: typeof SettingsDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/design': {
      id: '/settings/design'
      path: '/settings/design'
      fullPath: '/settings/design'
      preLoaderRoute: typeof SettingsDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SettingsDesignRoute: SettingsDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
