/**
 * User Builder
 *
 * Implements the Builder pattern for creating User objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type {
  UserInterface,
  UserPlan,
  TokenStatus,
  UserFeatures,
  UserState,
  UserSettings,
  UserDBVersion,
} from "./user.interface";
import { UserSchema } from "./user.schema";

/**
 * UserBuilder class
 *
 * Provides a fluent API for building User objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class UserBuilder {
  private data: Partial<UserInterface> = {};

  constructor() {
    // Set sensible defaults
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      username: "user",
      plan: "free",
      lastLogin: now,
      createDate: now,
    };
  }

  /**
   * Set the user ID (optional, auto-generated by default)
   * @param id - UUID for the user
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set the username
   * @param username - Login username
   * @returns this builder for chaining
   */
  username(username: string): this {
    this.data.username = username;
    return this;
  }

  /**
   * Set the display name
   * @param displayName - Display name
   * @returns this builder for chaining
   */
  displayName(displayName: string): this {
    this.data.displayName = displayName;
    return this;
  }

  /**
   * Set the avatar URL
   * @param avatar - Avatar URL
   * @returns this builder for chaining
   */
  avatar(avatar: string): this {
    this.data.avatar = avatar;
    return this;
  }

  /**
   * Set the email
   * @param email - User email
   * @returns this builder for chaining
   */
  email(email: string): this {
    this.data.email = email;
    return this;
  }

  /**
   * Set the last login timestamp
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  lastLogin(timestamp: string): this {
    this.data.lastLogin = timestamp;
    return this;
  }

  /**
   * Set the create date timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  createDate(timestamp: string): this {
    this.data.createDate = timestamp;
    return this;
  }

  /**
   * Set the subscription plan
   * @param plan - User plan (free/premium)
   * @returns this builder for chaining
   */
  plan(plan: UserPlan): this {
    this.data.plan = plan;
    return this;
  }

  /**
   * Set the plan start date
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  planStartDate(timestamp: string): this {
    this.data.planStartDate = timestamp;
    return this;
  }

  /**
   * Set the plan expiration date
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  planExpiresAt(timestamp: string): this {
    this.data.planExpiresAt = timestamp;
    return this;
  }

  /**
   * Set the trial expiration date
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  trialExpiresAt(timestamp: string): this {
    this.data.trialExpiresAt = timestamp;
    return this;
  }

  /**
   * Set the authentication token
   * @param token - Auth token string
   * @returns this builder for chaining
   */
  token(token: string): this {
    this.data.token = token;
    return this;
  }

  /**
   * Set the token status
   * @param status - Token validation status
   * @returns this builder for chaining
   */
  tokenStatus(status: TokenStatus): this {
    this.data.tokenStatus = status;
    return this;
  }

  /**
   * Set the last token check timestamp
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  lastTokenCheck(timestamp: string): this {
    this.data.lastTokenCheck = timestamp;
    return this;
  }

  /**
   * Set the server message
   * @param message - Server message string
   * @returns this builder for chaining
   */
  serverMessage(message: string): this {
    this.data.serverMessage = message;
    return this;
  }

  /**
   * Set the user features
   * @param features - User feature permissions
   * @returns this builder for chaining
   */
  features(features: UserFeatures): this {
    this.data.features = features;
    return this;
  }

  /**
   * Set the user state
   * @param state - User application state
   * @returns this builder for chaining
   */
  state(state: UserState): this {
    this.data.state = state;
    return this;
  }

  /**
   * Set the user settings
   * @param settings - User settings/preferences
   * @returns this builder for chaining
   */
  settings(settings: UserSettings): this {
    this.data.settings = settings;
    return this;
  }

  /**
   * Set the database version info
   * @param dbVersion - DB version info
   * @returns this builder for chaining
   */
  dbVersion(dbVersion: UserDBVersion): this {
    this.data.dbVersion = dbVersion;
    return this;
  }

  /**
   * Build and validate the User object
   * @returns A validated UserInterface object
   * @throws ZodError if validation fails
   */
  build(): UserInterface {
    // Update lastLogin to current time if not explicitly set after construction
    const now = dayjs().toISOString();
    if (!this.data.lastLogin) {
      this.data.lastLogin = now;
    }
    if (!this.data.createDate) {
      this.data.createDate = now;
    }

    // Validate and return
    const result = UserSchema.parse(this.data);
    return result as UserInterface;
  }

  /**
   * Build a partial User object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial UserInterface object with updated lastLogin
   */
  buildPartial(): Partial<UserInterface> {
    // Always update lastLogin for partial builds
    this.data.lastLogin = dayjs().toISOString();
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      username: "user",
      plan: "free",
      lastLogin: now,
      createDate: now,
    };
    return this;
  }
}
