name: novel-editor-app
base: core22
version: '0.1.8'
summary: 一个现代化的小说编辑器
description: |
  Novel Editor 是一个功能强大的小说编辑器，提供丰富的编辑功能和直观的用户界面。
  
  主要特性：
  - 富文本编辑
  - 章节管理
  - 角色管理
  - 大纲视图
  - 导出为多种格式

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  novel-editor:
    command: bin/novel-editor
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - removable-media

parts:
  novel-editor:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - file
      - unzip
      - libwebkit2gtk-4.1-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - patchelf
      - build-essential
      - pkg-config
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libgtk-3-0
      - libayatana-appindicator3-1
      - librsvg2-2
    override-build: |
      set -eux
      
      echo "=== Installing Bun ==="
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun --version
      
      echo "=== Installing Rust ==="
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      export PATH="$HOME/.cargo/bin:$PATH"
      rustc --version
      cargo --version
      
      echo "=== Installing root dependencies ==="
      cd $CRAFT_PART_SRC
      bun install
      
      echo "=== Installing desktop dependencies ==="
      cd apps/desktop
      bun install
      
      echo "=== Building desktop frontend ==="
      bun run build
      
      # 验证构建输出
      if [ ! -d "dist" ]; then
        echo "ERROR: Frontend build failed - dist directory not found"
        exit 1
      fi
      
      echo "=== Building Tauri application ==="
      # 使用 bun 运行 tauri（会自动使用 node_modules 中的 @tauri-apps/cli）
      bun run tauri build --bundles deb
      
      echo "=== Extracting deb package ==="
      DEB_FILE=$(find src-tauri/target/release/bundle/deb -name "*.deb" | head -n 1)
      if [ -z "$DEB_FILE" ]; then
        echo "ERROR: No deb file found"
        exit 1
      fi
      
      echo "Found deb: $DEB_FILE"
      dpkg-deb -x $DEB_FILE $CRAFT_PART_INSTALL
      
      echo "=== Setting up binary ==="
      mkdir -p $CRAFT_PART_INSTALL/bin
      
      # 列出解压后的内容以便调试
      echo "Contents of CRAFT_PART_INSTALL:"
      find $CRAFT_PART_INSTALL -type f -name "novel-editor*" 2>/dev/null || true
      
      # 查找并复制二进制文件（使用 cp 而非 mv，更安全）
      BINARY_PATH=$(find $CRAFT_PART_INSTALL -type f -name "novel-editor" -executable | head -n 1)
      if [ -n "$BINARY_PATH" ]; then
        echo "Found binary at: $BINARY_PATH"
        cp "$BINARY_PATH" $CRAFT_PART_INSTALL/bin/novel-editor
        chmod +x $CRAFT_PART_INSTALL/bin/novel-editor
      else
        echo "ERROR: Binary not found, listing all files:"
        find $CRAFT_PART_INSTALL -type f
        exit 1
      fi
      
      echo "=== Verifying binary ==="
      ls -la $CRAFT_PART_INSTALL/bin/
      
      echo "=== Build completed successfully ==="
