/**
 * Attachment Builder
 *
 * Implements the Builder pattern for creating Attachment objects.
 * Provides a fluent API with chainable methods for setting properties.
 *
 * @requirements 3.1, 3.2
 */

import { v4 as uuidv4 } from "uuid";
import dayjs from "dayjs";
import type { AttachmentInterface, AttachmentType } from "./attachment.interface";
import { AttachmentSchema } from "./attachment.schema";

/**
 * AttachmentBuilder class
 *
 * Provides a fluent API for building Attachment objects with:
 * - Sensible defaults for optional properties
 * - Method chaining for clean, readable code
 * - Zod validation on build()
 */
export class AttachmentBuilder {
  private data: Partial<AttachmentInterface> = {};

  constructor() {
    // Set sensible defaults
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      type: "file",
      fileName: "",
      filePath: "",
      uploadedAt: now,
    };
  }

  /**
   * Set the attachment ID (optional, auto-generated by default)
   * @param id - UUID for the attachment
   * @returns this builder for chaining
   */
  id(id: string): this {
    this.data.id = id;
    return this;
  }

  /**
   * Set the associated project ID
   * @param projectId - Project UUID
   * @returns this builder for chaining
   */
  project(projectId: string): this {
    this.data.project = projectId;
    return this;
  }

  /**
   * Set the attachment type
   * @param type - Attachment type (image/audio/file)
   * @returns this builder for chaining
   */
  type(type: AttachmentType): this {
    this.data.type = type;
    return this;
  }

  /**
   * Set the file name
   * @param fileName - Original file name
   * @returns this builder for chaining
   */
  fileName(fileName: string): this {
    this.data.fileName = fileName;
    return this;
  }

  /**
   * Set the file path
   * @param filePath - File storage path
   * @returns this builder for chaining
   */
  filePath(filePath: string): this {
    this.data.filePath = filePath;
    return this;
  }

  /**
   * Set the upload timestamp (optional, auto-generated by default)
   * @param timestamp - ISO 8601 datetime string
   * @returns this builder for chaining
   */
  uploadedAt(timestamp: string): this {
    this.data.uploadedAt = timestamp;
    return this;
  }

  /**
   * Set the file size
   * @param size - File size in bytes
   * @returns this builder for chaining
   */
  size(size: number): this {
    this.data.size = size;
    return this;
  }

  /**
   * Set the MIME type
   * @param mimeType - MIME type string
   * @returns this builder for chaining
   */
  mimeType(mimeType: string): this {
    this.data.mimeType = mimeType;
    return this;
  }

  /**
   * Build and validate the Attachment object
   * @returns A validated AttachmentInterface object
   * @throws ZodError if validation fails
   */
  build(): AttachmentInterface {
    // Ensure uploadedAt is set
    if (!this.data.uploadedAt) {
      this.data.uploadedAt = dayjs().toISOString();
    }

    // Validate and return
    const result = AttachmentSchema.parse(this.data);
    return result as AttachmentInterface;
  }

  /**
   * Build a partial Attachment object for update operations
   * Does not require all fields, only validates provided fields
   * @returns A partial AttachmentInterface object
   */
  buildPartial(): Partial<AttachmentInterface> {
    return { ...this.data };
  }

  /**
   * Reset the builder to initial state
   * Useful for reusing the same builder instance
   * @returns this builder for chaining
   */
  reset(): this {
    const now = dayjs().toISOString();
    this.data = {
      id: uuidv4(),
      type: "file",
      fileName: "",
      filePath: "",
      uploadedAt: now,
    };
    return this;
  }
}
